### ISSUE TITLE
Potential optimization: ENTER/LEAVE on 286+/etc. platforms

### ISSUE THREAD

**Issue by asiekierka** [tkchia/gcc-ia16#100]
From my reading of opcode tables, it seems that, barring the 80186/80188 itself, using ENTER for speed-optimized (rather than size-optimized) code might be a bad idea.

* 80186 (a): ENTER imm16, 0 => 15 cycles
* 80186 (b): PUSH reg + MOV reg, reg + SUB reg, reg => 15 cycles
* 80286 (a): ENTER imm16, 0 => 11 cycles
* 80286 (b): PUSH reg + MOV reg, reg + SUB reg, reg => 7 cycles

On platforms like the V30MZ with more complex pipelines, it seems to be even more dire.

I'm unfortunately not familiar enough with GCC internals to know how to implement this (I'd gladly take hints from someone more experienced and try to do so myself), but I think that for some platforms ENTER (and possibly LEAVE) should be used only as a size optimization, not a speed optimization.

Apologies if this isn't right - this is my second time messing with GCC internals, and I'm not an 8086 expert.

**Comment by tkchia** [comment]
Hello @asiekierka,

Thanks for your report!  I have pushed a commit to add the costs of `enter` and `leave` to the instruction cost tables, and to get the back-end to use these costs to decide whether to use `enter` and/or `leave`.  Hopefully this works.

The output of function prologues and epilogues is currently controlled by the functions `ia16_expand_prologue ()` and `ia16_expand_epilogue (·)`, which are in turn triggered by the `"prologue"` and `"epilogue"` insn patterns in the `ia16.md` machine description file.  `ia16_expand_prologue ()` used to be hard-coded to _always_ try to use `enter` whenever this instruction is available.

> this is my second time messing with GCC internals

We are all learning here. :slightly_smiling_face:  I started learning about GCC internals from the `gccint` info page.  This should be available on your installation through

> `$ info` _...installation-prefix..._`/share/info/gccint.info`

The "Machine Desc" and "Target Macros" sections describe the general interface expected of the `.md` files and `.c` that comprise a target back-end.  Other than that, the `gccint` info page also talks a bit about routines and variables in the machine-independent middle-end, that one can use.  (Though, unfortunately, there are still some things you can only figure out through the source code.)

> and I'm not an 8086 expert.

You are _definitely_ being modest here. :slightly_smiling_face: 

Thank you!

**Comment by asiekierka** [comment]
Thank you! Works fine here.

I'd like to be able to contribute more deeply in the future, so these hints are very useful.

**Comment by asiekierka** [comment]
Left one question here: https://github.com/tkchia/gcc-ia16/commit/9bbbb8ffa1bbf26137d6521e2d8e3d95ddfe44af#r73682880

**Comment by ecm-pushbx** [comment]
I also have a question, I don't see `-Os` handling anywhere? `enter` is size-better than `push` \ `mov` \ `sub` and `leave` is always at least size-equal to `pop` (or better than `mov` \ `pop`). So if `-Os` is selected and 186+ instructions are available then in those cases `enter` and `leave` should be used.

**Comment by tkchia** [comment]
Hello @asiekierka,

> Is there a reason to use `<` over `<=` here? If the two costs are equal, ENTER still has a size advantage (when two speeds are equal, optimizing for size is a reasonable principle IMO). Same for LEAVE.

You have a point &mdash; I will make the change.

Hello @ecm-pushbx,

> I also have a question, I don't see `-Os` handling anywhere?

`-Os` is handled by the cost table `ia16_size_costs` (which appears beneath the function `ia16_size_address_cost (`...`)`).  In this cost table, the cost values correspond roughly to byte counts, rather than cycle counts.

(I now see that the indentation in the definition of `ia16_size_costs` is a bit off.  This probably explains why the name did not show up in the commit's diff.  I should probably fix that too. :neutral_face: )

Thank you!

**Comment by tkchia** [comment]
I have pushed a further Git commit: https://github.com/tkchia/gcc-ia16/commit/12853ddca70e45c5d0ee561f44b7b0a1089b7959 .  Thank you!
