### ISSUE TITLE
Cannot use va_list, va_start, or va_end, when %ss != .data (-mno-callee-assume-ss-data-segment)

### ISSUE THREAD

**Issue by tkchia** [tkchia/gcc-ia16#104]
```
$ cat test2.c
#include <stdarg.h>

void
baz (const char *fmt, ...)
{
  va_list ap;
  va_start (ap, fmt);
  while (va_arg(ap, int) != 0);
  va_end (ap);
}
$ ia16-elf-gcc -S -Os test2.c -mno-callee-assume-ss-data-segment 
In file included from test2.c:1:0:
test2.c: In function ‘baz’:
test2.c:7:13: error: passing argument 1 of ‘__builtin_va_start’ from pointer to non-enclosed address space
   va_start (ap, fmt);
             ^
test2.c:9:11: error: passing argument 1 of ‘__builtin_va_end’ from pointer to non-enclosed address space
   va_end (ap);
           ^
```
The issue was first surfaced by @asiekierka, at https://github.com/tkchia/gcc-ia16/issues/102#issuecomment-1128128252 .

**Comment by tkchia** [comment]
Starting a new Git branch [`tkchia/va-list`](https://github.com/tkchia/gcc-ia16/tree/tkchia/va-list) to deal with this stuff...

**Comment by tkchia** [comment]
`va_list` + `-no-callee-assume-ss-data-segment` should work now, with the latest commits 5f8df20de5ea8b4cc77e849a18956fea7a6e73f3, 65e74b7c2c97d556efaec6b3789585b6eb454e25, e4f7308de1f077789f834a108a2f481311f156ea, d43023acc79e261459a9980c5b8551cb87547f18, and 9336aa4050e418ea80e86c60e874957132decaf5.

**Comment by asiekierka** [comment]
Can confirm. Thank you!
