### ISSUE TITLE
FreeDOS kernel build of a PR fails with ppa of gcc-ia16

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#108]
I submitted [a pull request](https://github.com/FDOS/kernel/pull/72) to the FreeDOS kernel.

In [this build log](https://github.com/FDOS/kernel/runs/6537323836?check_suite_focus=true) the linking command fails:

```
ia16-elf-gcc -Tkernel.ld -Wl,-Map,kernel.map -o kernel.exe kernel.obj entry.obj io.obj console.obj serial.obj printer.obj dsk.obj sysclk.obj asmsupt.obj execrh.obj nlssupt.obj procsupt.obj dosidle.obj int2f.obj nls_hc.obj apisupt.obj intr.obj irqstack.obj blockio.obj chario.obj systime.obj error.obj break.obj dosfns.obj fatdir.obj fatfs.obj fattab.obj fcbfns.obj inthndlr.obj ioctl.obj memmgr.obj task.obj newstuff.obj nls.obj network.obj prf.obj misc.obj strings.obj syspack.obj lfnapi.obj iasmsupt.obj memdisk.obj main.obj config.obj initoem.obj inithma.obj dyninit.obj iprf.obj initdisk.obj initclk.obj cpu.obj -Wl,--whole-archive ../drivers/device.lib -Wl,--no-whole-archive # @KGC8632.lnk;
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/../../../../../ia16-elf/bin/ld:kernel.ld:89: nonconstant expression for load base
collect2: error: ld returned 1 exit status
```

**Comment by ecm-pushbx** [comment]
Using the gcc-ia16 installed on our server the kernel builds just fine however. This was built on 2021-11-13.

**Comment by ecm-pushbx** [comment]
This is the line referenced in the error message: https://github.com/FDOS/kernel/blob/8c8d21311974e3274b3c03306f3113ee77ff2f45/kernel/kernel.ld#L89

**Comment by andrewbird** [comment]
Unsurprisingly I see the same thing here. There have only been 5 commits to ia16's binutils since the last commit to FDOS/kernel so I was going to try an older version from the PPA, but there is only the latest available.

Hello @tkchia, it seems the kernel linker script no longer works with the current binutils, have you any hints on what we may need to change to suit? I tried replacing `SIZEOF(.data)` with a computed value and it didn't help, so I think the problem lies with `LOADADDR(.data)`

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx, hello @andrewbird,

On my system, the (partial) link map (`kernel/kernel.map`) showed that the linker was trying to rope in object modules from the Newlib C library.  You need a `-nostdlib` option somewhere on the linker command line.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia, @ecm-pushbx 
   That worked just great, now it links just fine.

@ecm-pushbx, would you care to add this to your PR?
```diff
diff --git a/mkfiles/gcc.mak b/mkfiles/gcc.mak
index 189c267..b2b51a4 100644
--- a/mkfiles/gcc.mak
+++ b/mkfiles/gcc.mak
@@ -72,7 +72,7 @@ INITPATCH=ia16-elf-objcopy --redefine-sym ___umodsi3=_init_umodsi3 --redefine-sy
 CLDEF=1
 CLT=gcc -DDOSC_TIME_H -I../hdr -o $@
 CLC=$(CLT)
-LINK=$(XLINK) -Tkernel.ld -Wl,-Map,kernel.map -o kernel.exe $(OBJS) -Wl,--whole-archive ../drivers/device.lib -Wl,--no-whole-archive \#
+LINK=$(XLINK) -Tkernel.ld -nostdlib -Wl,-Map,kernel.map -o kernel.exe $(OBJS) -Wl,--whole-archive ../drivers/device.lib -Wl,--no-whole-archive \#
 
 .SUFFIXES: .obj .asm
```

Thank you!

**Comment by ecm-pushbx** [comment]
Added a commit with just that patch, it seems to still work fine on our (older) gcc-ia16 toolchain so it seems like it will be fine.

**Comment by ecm-pushbx** [comment]
This is odd, I am now getting something else which the build seems to fail with. There isn't any error message but it appears that linking the SHARE application fails too. Does that also need the -nostdlib switch perhaps?

```
ia16-elf-gcc -mtsr -Wall -fpack-struct -mcmodel=tiny -c share.c -o share.obj -Os
nasm -f elf -I ../lmacros/ -I lmacros/ gcc_help.asm -o gcc_help.obj
ia16-elf-gcc -mtsr share.obj gcc_help.obj -o share.com -li86 -Wl,-Map=share.map
Error: Process completed with exit code 8.
```

Link: https://github.com/FDOS/kernel/runs/6538487941?check_suite_focus=true

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Running `bash -x ./ci_build.sh` on my machine gives the failing command:
```
+ '[' '!' -d _watcom ']'
+ '[' -f ow-snapshot.tar.gz ']'
+ wget --quiet https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
```
It seems that Mr. Malak is now releasing snapshots for OW in `.xz` format and not `.gz` format, so the script will need to be updated.  (Also, perhaps try running `wget` wihout `--quiet` ...?)

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
  Thanks again for the fix. Though I'd prefer it if the --quiet was swapped for --no-verbose as otherwise we get all the progress dots printed!
~~~
       --no-verbose
           Turn off verbose without being completely quiet (use -q for that), which means that error messages and basic information still get printed.
~~~
   It seems that I'll have to update all the other repos I have that build with Watcom too!

Hello @ecm-pushbx,
   something like this should suffice but feel free to implement as you like.
```diff
diff --git a/ci_build.sh b/ci_build.sh
index c0024cf..61e3d91 100755
--- a/ci_build.sh
+++ b/ci_build.sh
@@ -11,9 +11,11 @@ echo BUILD_DIR is \"${BUILD_DIR}\"
 rm -rf _output
 mkdir _output
 
+OWTAR=ow-snapshot.tar.xz
+
 # GCC
 mkdir _output/gcc
-git clean -x -d -f -e _output -e _watcom -e ow-snapshot.tar.gz
+git clean -x -d -f -e _output -e _watcom -e $OWTAR
 make -C country clean
 make all COMPILER=gcc
 mv -n bin/KGC*.map bin/KGC*.sys _output/gcc/.
@@ -25,17 +27,17 @@ mv -n share/share.map _output/gcc/.
 
 # Watcom
 if [ ! -d _watcom ] ; then
-  [ -f ow-snapshot.tar.gz ] || wget --quiet https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
+  [ -f $OWTAR ] || wget --no-verbose https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/$OWTAR
 
   mkdir _watcom
-  (cd _watcom && tar -xf ../ow-snapshot.tar.gz)
+  (cd _watcom && tar -xf ../$OWTAR)
 fi
 
 export PATH=$BUILD_DIR/bin:$PATH:$BUILD_DIR/_watcom/binl64
 export WATCOM=$BUILD_DIR/_watcom
 
 mkdir _output/wc
-git clean -x -d -f -e _output -e _watcom -e ow-snapshot.tar.gz
+git clean -x -d -f -e _output -e _watcom -e $OWTAR
 make -C country clean
 make all COMPILER=owlinux
 mv -n bin/KWC*.map bin/KWC*.sys _output/wc/.
```
Thank you.
