### ISSUE TITLE
FreeDOS kernel: local array of structs initialised from init data segment uses wrong memcpy

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#109]
Refer to https://github.com/FDOS/kernel/issues/73 :

> **gcc kernel crash upon initialisation, due to using HMATEXT memcpy implicitly in DoConfig**
>
> I assume this crash was introduced by [ee255d2](https://github.com/FDOS/kernel/commit/ee255d23551dc9160ddd32203d34bbc890f39fbc)
> 
> I tested that the kernel still did build with gcc, but I failed to test whether it also still runs. Turns out that apparently changing the pointers to static made it so gcc put the structure into the init data segment and implicitly called `memcpy` to put it on the stack. That's wrong, however. We depend on `#define` to convert all calls in init to the init text copies of `memcpy` etc. The implicit call by gcc however attempts to call the HMA text copy of `memcpy` which happens to be at another offset.
> 
> Sorry for this headache! I will test a fix soon.

This is the commit that introduced the crash: https://github.com/FDOS/kernel/commit/ee255d23551dc9160ddd32203d34bbc890f39fbc It changed the code from:

```
    char * configfile = "";
    char * altconfigfile = "fdconfig.sys";
    char * oldconfigfile = "config.sys";
    struct { char ** pointer; char const * command; }
      configcommands[] = {
        { &configfile, "CONFIG" },
        { &altconfigfile, "ALTCONFIG" },
        { &oldconfigfile, "OLDCONFIG" },
        { NULL, NULL }
        };
```

to:

```
    static char * configfile = "";
    static char * altconfigfile = "fdconfig.sys";
    static char * oldconfigfile = "config.sys";
    struct { char ** pointer; char const * command; }
      configcommands[] = {
        { &configfile, "CONFIG" },
        { &altconfigfile, "ALTCONFIG" },
        { &oldconfigfile, "OLDCONFIG" },
        { NULL, NULL }
        };
```

(This was needed because OpenWatcom complained that the `&configfile` initialisation of the pointer to pointer field wasn't constant when `char * configfile` was local on the stack frame.)

**Comment by ecm-pushbx** [comment]
As a fix I declared the array itself `static` now. However, I think we should consider a better solution if it is possible, such as telling the compiler to use `init_memcpy` in cases like this.

**Comment by ecm-pushbx** [comment]
In the assembly source the labels are [defined here](https://github.com/FDOS/kernel/blob/ee255d23551dc9160ddd32203d34bbc890f39fbc/kernel/asmsupt.asm#L53) and `memcpy` is [declared here](https://github.com/FDOS/kernel/blob/ee255d23551dc9160ddd32203d34bbc890f39fbc/kernel/asmsupt.asm#L148). And [here in the init-mod header](https://github.com/FDOS/kernel/blob/ee255d23551dc9160ddd32203d34bbc890f39fbc/kernel/init-mod.h#L52) we use `#define` to redirect explicit calls to `memcpy` to use `init_memcpy`.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Well, I suppose you can try to take advantage of the `$(INITPATCH)` command line in `mkfiles/gcc.mak`, to map calls to `memcpy`, `memset`, etc. in the initialization code to the `INIT_TEXT` entry points for these routines &mdash; similar to what is now done for the `libgcc` routines `__umodsi3`, `__udivsi3`, etc.

GCC produces implicit libcalls to `memcpy` and friends in the same way as it produces libcalls to `__umodsi3` etc., so the same `--redefine-sym` trick should work to redirect the calls.

Thank you!

**Comment by ecm-pushbx** [comment]
Tested this and it does seem to work, thanks. I might submit this as a PR to the kernel soon. Test patch in https://pushbx.org/ecm/test/20220522/freedos-kernel-initpatch-test.diff (Reverting the array to non-static is just to test the difference, it can stay as static for actual use.)
