### ISSUE TITLE
Medium model data relocations not emitted for ELKS?

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#117]
In the process of porting the D-Flat TUI library to ELKS, which requires medium model due to code size, it seems that the .data section R_SEGWORD segment relocations are not being emitted at final link time, at least for the version of the ld.gold linker (or elf2elks perhaps) ELKS is running (ld.gold is a bit old, but elf2elks should be current). I'm wondering whether this might have changed in the last year or so (after the medium model work was first completed by both of us on ELKS).

The compilation options being used are:
`-fno-inline -melks-libc -mcmodel=medium -msegment-relocation-stuff -mtune=i8086 -Wall -Os -ffunction-sections`

In particular, the a.out supplemental header msh_drsize longword is always 0, despite some .data segment relocations being emitted into the .o files: 
```
normal.o:     file format elf32-i386

Disassembly of section .data:

00000000 <classdefs>:
   0:   ff                      (bad)
   1:   ff 00                   incw   (%bx,%si)
            2: R_386_16 NormalProc
            2: R_386_SUB16  NormalProc!
    ...
            4: R_386_SEG16  NormalProc!
            a: R_386_16 ApplicationProc
            a: R_386_SUB16  ApplicationProc!
   b:   00 00                   add    %al,(%bx,%si)
            c: R_386_SEG16  ApplicationProc!
   d:   00 c0                   add    %al,%al
```
It took some time to debug this, but the `classdefs` array above stores a 4-byte function pointer at byte offsets 2-5 as can be seen above (and then again at offsets 0x0A-0x0D etc). What is happening is the segment value of the function pointer stored in the .data section is always 0x1000, rather than the CS-relocated value. I was able to get this to work for the time being by storing a properly-runtime-relocated .text/.fartext-based function pointer into the array at runtime startup, after which all works well (here's a cool screenshot):

<img width="832" alt="ELKS dflat" src="https://user-images.githubusercontent.com/11985637/178190637-e97663ef-2e74-4a7a-b3a4-5e2d1c1ca480.png">

The TUI library is rather large, and I thought to ask what you think about this before going to the trouble of producing a smaller sample and/or download a later ia16 tree to reproduce the problem. Dumping the a.out file header always shows the `msh_drsize` longword as 0. Checking the ELKS loader at elks/fs/exec.c, I see we do support relocating .data relocations, but IIRC this has never been tested, as we'd never produced an executable that required .data segment relocations.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

Argh!  Let me look into this.  If `.msh_drsize` is always 0, then the bug is probably happening at link time, rather than at run time.  I should probably check first if `elf2elks` is doing anything bogus.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

Yep, I am able to reproduce the problem by storing a function pointer inside static data storage:
```
#include <stdio.h>

static int 
w00t (void)
{
  return 1337;
}

int (*pf) (void) = w00t;

int
main (void)
{
  printf ("%d\n", (*pf) ());
  return 0;
}
```
(Since the functions are far in the medium model, any function pointers will also have to be far pointers.)

My guess is that D-Flat was also using function pointers in a similar way.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

There was a totally silly oversight on my part. :slightly_frowning_face:   `elf2elks` did compute the relocations to apply to the data segment, but forgot to compute the `.msh_drsize` field.  I will submit a quick pull request to fix this.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thank you for the very quick fix, it is much appreciated, and everything now works properly.

> My guess is that D-Flat was also using function pointers in a similar way.

Yes, exactly the same way - the 4-byte function pointers are stored in the .data segment, and now relocated properly by the kernel at load time.

On the subject of `elkf2elks` fixes and/or enhancements - as part of the instrumentation work I'm doing using `ia16-elf-gcc`, I have developed a compressed symbol file format that is used for displaying a process's stack function call backtrace at runtime. The symbol table is being added to the end of the executable file, and the a.out `syms` member being used to allow the application to access the symbol table from itself at runtime. It would be nice to have an `elf2elks` option that would write this symbol table, rather than using another tool. Are you interested in discussing such an enhancement? If so, I'll open another issue for it.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> It would be nice to have an `elf2elks` option that would write this symbol table, rather than using another tool. Are you interested in discussing such an enhancement? If so, I'll open another issue for it.

That will be cool &mdash; thanks!  It seems `elks/arch/i86/tools/a.out.h` has some sort of symbol table format definition, but as far as I can tell nobody uses that, so we can probably break compatibility with it...

Thank you!
