### ISSUE TITLE
Undefined references on ELKS kernel with compiler upgrade

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#118]
Hello @tkchia,

In pre-preparation for using the `-mno-post-link` option, I upgraded the ELKS toolchain build to the latest versions, from the prior version that was almost two years old:
```
$ git diff
diff --git a/tools/Makefile b/tools/Makefile
index 024f3d60..328352a0 100644
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -23,7 +23,7 @@ BUILDDIR=$(CROSSDIR)/build
 
 # BINUTILS for IA16
 
-BINUTILS_VER=164dc55d3d9488a487d39c2e7f3f8cadf6dc12f5
+BINUTILS_VER=1d7535fd03bdddf979d63fcd0072aa68129971fc
 BINUTILS_DIST=binutils-ia16-$(BINUTILS_VER)
 
 $(DISTDIR)/$(BINUTILS_DIST).tar.gz:
@@ -97,7 +97,7 @@ $(DISTDIR)/$(MPC_DIST).tar.gz:
 
 # GCC for IA16
 
-GCC_VER=17bd8a491ca31f8fd867b1f1a380cbbc5ef53b07
+GCC_VER=c763cb6e365eee543c812435354e0cba7d61e235
 GCC_DIST=gcc-ia16-$(GCC_VER)
 
 $(DISTDIR)/$(GCC_DIST).tar.gz:
```
The compiler and binutils built fine.

From the current ELKS source tree, a `make clean; make all` produces some of the following undefined references. Do you have thoughts on why this may be? I haven't yet dug into it, no options were changed, but we are using `-ffreestanding`:
```
ia16-elf-gcc -ffreestanding -fno-inline -melks -mcmodel=small -msegment-relocation-stuff   -I/Users/greg/net/elks-gh/include -I/Users/greg/net/elks-gh/elks/include -I/Users/greg/net/elks-gh/libc/include -D__KERNEL__ -Os -fno-delete-null-pointer-checks -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body -c -o el3.o el3.c
ia16-elf-ar rcs net_drv.a  ne2k-asm.o ne2k.o wd.o el3-asm.o el3.o
ia16-elf-gcc -E -traditional -I/Users/greg/net/elks-gh/include -I/Users/greg/net/elks-gh/elks/include -I/Users/greg/net/elks-gh/libc/include -D__KERNEL__ -o boot/crt0.tmp boot/crt0.S
ia16-elf-as   --32-segelf -o boot/crt0.o boot/crt0.tmp
rm boot/crt0.tmp
(cd ../.. ; ia16-elf-ld.gold  -M  -T /Users/greg/net/elks-gh/elks/elks-small.ld \
		arch/i86/boot/crt0.o \
		init/main.o '-(' fs/fs.a kernel/kernel.a lib/lib.a net/net.a fs/minix/minixfs.a fs/msdos/msdos.a arch/i86/kernel/akernel.a arch/i86/lib/lib86.a arch/i86/mm/mm.a  arch/i86/drivers/char/chr_drv.a arch/i86/drivers/block/blk_drv.a arch/i86/drivers/net/net_drv.a '-)' "`ia16-elf-gcc -ffreestanding -fno-inline -melks -mcmodel=small -msegment-relocation-stuff   -I/Users/greg/net/elks-gh/include -I/Users/greg/net/elks-gh/elks/include -I/Users/greg/net/elks-gh/libc/include -D__KERNEL__ -Os -fno-delete-null-pointer-checks -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body -print-libgcc-file-name`" \
		-o arch/i86/boot/system > arch/i86/boot/system.map ; \
		ia16-elf-nm arch/i86/boot/system > arch/i86/boot/system-nm.map; \
		elf2elks  arch/i86/boot/system)
init/main.o:function parse_dev: error: undefined reference to '__ia16_far_call_thunk.bx.6!'
init/main.o:function parse_dev: error: undefined reference to '__ia16_far_call_thunk.bx.6!'
...
fs/msdos/msdos.a(misc.o):function msdos_add_cluster: error: undefined reference to '__modsi3!'
fs/msdos/msdos.a(misc.o):function msdos_add_cluster: error: undefined reference to '__modsi3!'
fs/msdos/msdos.a(misc.o):function msdos_add_cluster: error: undefined reference to '__udivsi3!'
...
```

This should be immediately reproducible using the latest version of the compiler and ELKS source.
Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> ... ``"`ia16-elf-gcc -ffreestanding -fno-inline -melks -mcmodel=small -msegment-relocation-stuff`` ... ``-print-libgcc-file-name`"``

Argh.  It looks like the new compiler was confused by the appearance of _both_ `-ffreestanding` and `-melks` at the same time, and it ended up selecting the wrong version of `libgcc.a` from the compiler installation (which happens to lack the `segelf` segment base symbols `__modsi3!` etc.).

Let me see how I can fix this in the `gcc-ia16` front-end.

Thank you!

**Comment by ghaerr** [comment]
Thanks, I'm glad you were able to quickly understand what is happening.

Do we need `-ffreestanding` for the kernel build? I don't know exactly what it turns off, whether it is the printf-esque descriptors for C library calls and such, or whether it is intended for systems that supply their own libgcc functions, at some point.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Do we need `-ffreestanding` for the kernel build?

Probably not, I suspect...  If any implementations of `printf`, `memcmp`, `strlen`, etc. in the kernel have the same semantics as expected in a hosted environment, and it is safe for the compiler to e.g. replace a call to `strlen` with its own custom code, then we might be able to get away with pretending that the kernel is just a normal hosted program.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> If any implementations of printf, memcmp, strlen, etc. in the kernel have the same semantics as expected in a hosted environment, and it is safe for the compiler to e.g. replace a call to strlen with its own custom code, then we might be able to get away with pretending that the kernel is just a normal hosted program.

Ok, I'll look into that as a workaround for the situation. But it would probably be best to allow both `-ffreestanding` and `-melks` in the longer term. 

Is there a list of the functions considered to be standardized, when `-ffreestanding` is not set? I'm aware of `printf("\n") -> puts("\n")` and such, but don't have a complete list, which could be worthwhile. I understand that __builtin_xxx calls are handled separately with another switch, although unsure when __builtin_strcpy might be used. And I had thought gcc required `memcpy`, `memset` and a couple other low level routines (outside of libgcc), which it called (e.g. on structure returns/copies) and required the same semantics as the C library equivalents.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Is there a list of the functions considered to be standardized, when `-ffreestanding` is not set?

There is a list of these in GCC's info file (`info gcc`) under the section "Other Built-in Functions Provided by GCC".

Thank you!

**Comment by ghaerr** [comment]
Thank you @tkchia for the very fast fix! I confirm your PR fixes the problem.

On a side note, not sure if to do with libgcc or code generated, but when compiling the ELKS kernel, the newer version produces a kernel with the .text section 368 bytes larger (62064 -> 62432), and .fartext larger by 16 bytes (12304 -> 12320) bytes.
