### ISSUE TITLE
Feature request: ISR attribute to save call-used registers

### ISSUE THREAD

**Issue by asiekierka** [tkchia/gcc-ia16#119]
The calling convention used by gcc-ia16 (in regparmcall, at least) currently assumes that AX, BX, CX and DX can be clobbered by the callee. However, an interrupt service routine must save all registers it modifies to restore them before IRET - the existing `interrupt` attribute is fine for this, until an interrupt tries to call another, non-interrupt function. This could be mitigated by using `save_all` on every function called by the ISR, but I feel a good alternate option to provide would be an attribute which forces saving/restoring AX/BX/CX/DX as part of the ISR-marked function.

**Comment by tkchia** [comment]
Hello @asiekierka,

Hmm &mdash; the `interrupt` attribute on a function _should_ by right already take into account any registers that are modified by the function's callee.  If it does not actually save all registers that callees might use, then there might be a code correctness bug.  Let me look further into this.

Thank you!

**Comment by asiekierka** [comment]
It does take into account any registers modified by the function itself, but not ones modified by a function which is called *by* the function, or modified by a function... so forth. This makes sense - once you introduce things like, say, function pointers, you *cannot* guarantee a limited list of modified registers - anything that can be clobbered by the callee is fair game.

Sorry, I might be a little unclear. Take an ISR function A which calls function B. Function B can, by calling convention, clobber some registers - but function A must restore all clobbered registers to the pre-interrupt-call state.

**Comment by tkchia** [comment]
Hello @asiekierka,

Looks like there is a bug in `gcc-ia16` then.  By right the programmer should not need to care about what the callees do.  I will try to fix this issue and let you know.  Thanks for your report!

**Comment by asiekierka** [comment]
Ah, I think I got the registers lists swapped in my head - it's `AX, BX, CX, DX` which can be modified by the callee (including callees deeper down - no guarantee the caller keeps its own copy!), and these should therefore always be preserved by an ISR.

Sorry. The idea was right, but...

**Comment by asiekierka** [comment]
One last post. I'm going to explain my thought process, in case this is a case of the XY problem. I apologize for the spam.

I have a vertical blank interrupt handler on a WonderSwan program I am working on, which I wanted to write in C. This vertical blank handler `vblank_int_handler` calls a C function `input_update_vbl`, which then calls an ASM function (written in a `.S` file) `keypad_scan`. As per the [Calling Convention](https://github.com/tkchia/gcc-ia16/blob/gcc-6_3_0-ia16-tkchia/gcc/doc/invoke.texi#L17066-L17070):

>@code{ax}, @code{bx}, @code{cx}, and @code{dx} are call-used.

This means that I work under the assumption that `keypad_scan` can clobber `cx`. However, in debugging (just now - I was tracking a weird memory corruption issue and I had a hunch what was causing it, but no confirmation), I found that this clobbered `cx` travels all the way to the `iret` in `vblank_int_handler`. My assumption is that this is because no other instruction in the function call chain uses `cx`, so - as it is "call-used" - it is never appropriately restored before `iret`.

**Comment by asiekierka** [comment]
I can verify that this solved my problem. Thank you!
