### ISSUE TITLE
32bit dpmi mode?

### ISSUE THREAD

**Issue by stsp** [tkchia/gcc-ia16#129]
Currently -mdosx and -mdpmi seem
to do the same thing. Would it be
possible to re-purpose -mdpmi, or to
add -mdpmi32, so that the program is
started as a 32bit dpmi client?
This doesn't mean anything should
be changed in ia16-gcc because 32bit
dpmi client starts on a 16bit code segment.
cw32 does support the 32bit startup, it
looks into "system flags" in executable
to find out which dpmi mode is needed.
Besides, I made sure the code built with
ia16-gcc works perfectly under 32bit dpmi.
So would it be possible to add such possibility?

**Comment by tkchia** [comment]
Hello @stsp,

Maybe.  Are you talking about getting compiled programs to run under 32-bit-only DPMI hosts, such as `cwsdpmi.exe`?

It seems that CauseWay does indeed have a "dual mode" executable control flag, which will allow a program to be started under either a 16-bit-capable DPMI host or a 32-bit-only DPMI host.

So maybe I can modify the `gcc-ia16` toolchain to use this flag.  I am not sure it is necessary to create a new `-m`... compiler switch for this.  But in any case... I will need to find a way to rigorously test everything.  One potential issue is whether (and how) this will affect callbacks to interrupt handlers, etc.

Thank you!

**Comment by stsp** [comment]
> Maybe. Are you talking about getting compiled programs to run under 32-bit-only DPMI hosts, such as
> cwsdpmi.exe?

Indeed.
They still start at 16bit CS so should
be fine. Though my use-case is slightly
different, I just use the ia16-gcc-compiled
djstub, which needs to switch to 32bit
DPMI by hands. And that's tricky and
non-portable.

**Comment by tkchia** [comment]
Hello @stsp,

I just added some code to the CauseWay DOS extender to specially handle `cwsdpmi.exe`, along with a regression test (https://github.com/tkchia/causeway/commit/8e8bc17e1d1a6bcf87f945e747204b90daed63b3 &middot; https://github.com/tkchia/causeway/commit/dcbc6c1de5cef24e98830088fcb9896af8dc7502).

A problem with `cwsdpmi.exe` is that it will not simply return an error if you try to switch to 16-bit DPMI mode, but will actually exit the whole program (&mdash; and there is no easy way to override this).

Now I "just" need to modify the `newlib-ia16` and `libi86` parts of the `gcc-ia16` toolchain to take advantage of CauseWay's dual mode facility. :wink: 

Thank you!

**Comment by stsp** [comment]
Good news, thanks!
Why do you need that "retry" strategy?
Are you planning some way (maybe a
new gcc switch?) to use 32bit for the
first time, wo trying 16bit first?

**Comment by tkchia** [comment]
Hello @stsp,

> Why do you need that "retry" strategy?

Well, the workaround for `cwsdpmi` is not really _needed_ for `gcc-ia16` 's particular case, I suppose.  But it might be useful in the general case (e.g. for `3P` program payloads that do not come from `gcc-ia16`).

> Are you planning some way (maybe a new gcc switch?) to use 32bit for the first time, wo trying 16bit first?

Is that something you want/need?  It should not be too hard to add such a switch &mdash; so I am kind of considering adding it &mdash; but that will of course mean more things to test (because there are more ways in which things can go wrong).

Thank you!

**Comment by stsp** [comment]
> Is that something you want/need?

Essentially.
I need a way to to create 32bit clients.
I suggest to just repurpose -mdpmi for
that, as it seems to be doing the same
thing as -mdosx right now.
The retry strategy may be good for
-mdosx in case cwsdpmi is already
loaded, but its not my case, I don't
need the retry strategy, I need 32bit
client. :)

**Comment by tkchia** [comment]
Hello @stsp,

> I don't need the retry strategy, I need 32bit client. :)

Ah, OK.  Let me see what I can do.

Thank you!

**Comment by tkchia** [comment]
Hello @stsp,

Just curious: which particular 32-bit DPMI function do you specifically need?  Thank you!

**Comment by stsp** [comment]
All of them. :)
I use ia16-gcc-compiled code as a
"loader" for a 32bit DPMI. Initially I
thought about the real-mode loader,
but it wasn't stable (because of %es
games) and I developed a way of
switching from 16 to 32 dpmi, but
that's not very portable.

**Comment by stsp** [comment]
You've seen it already in my opendos
test-case. The loader was used to run
comcom32.

**Comment by stsp** [comment]
BUT: I need none of the 32bit
functionality available from the
ia16-gcc-generated code itself.
I realize that libi86 may require
some work to correctly pass
args to 32bit dpmi functions, but
I've found that libi86 wraps only
a very few dpmi funcs anyway.
So I'll call them from asm in
either case.

**Comment by tkchia** [comment]
Hello @stsp,

> I realize that libi86 may require some work to correctly pass args to 32bit dpmi functions

Are there any particular DPMI functions which I should pay special attention to?

(I am in the process of getting `libi86` to work with CauseWay's dual mode &mdash; https://github.com/tkchia/libi86/commit/850d8c88eff6fe8b0387333f47cf3a1ee7783373.  It seems only `_spawnve` and friends (`int 0x21`, `ah` = `0x4b`) and `_dos_setvect` are causing problems so far, on my end.)

Thank you!

**Comment by stsp** [comment]
0xb, 0x203, 0x205, 0x212, 0x213,
0x303, 0x500,
0xc, 0xe, 0xf, 0x30X, 0x505, 0xc00,
0xd00.
This is the (probably) complete list
of DPMI funcs that use either 16 or
32bit reg as an argument, depending
on a client's mode.
It likely only means that when adapting
the existing 16bit code, one have to
make sure the high part of the needed
reg is cleared.

**Comment by stsp** [comment]
But in libi86 wrappers of that funcs,
you would need to allow the full 32bit
reg.

**Comment by tkchia** [comment]
Hello @stsp,

I added a `-mdosx32` option to `gcc-ia16` which will try to start the program under 32-bit DPMI, and if that fails, run it as a 16-bit DPMI program.  Let me know if you encounter any issues.

If there are any Watcom-style [`<dpmi.h>`](https://github.com/open-watcom/open-watcom-v2/blob/c1d9d3646bfd2bfc2e2c18da9c1e3dab4857cabc/bld/watcom/h/dpmi.h) functions which you would like to see implemented in the toolchain, do let me know too. :slightly_smiling_face: 

Thank you!

**Comment by stsp** [comment]
Thanks!
Yes, there is a problem.
When I was switching from 16
to 32bit dpmi by hands, I had to
"detach" the cw32 extender by
resetting all the intvectors that it
hooked. Now I do not do this, and
it appears cw32 doesn't support
32bit file I/O (when int21h is called
with size in ECX rather than in CX).

The simplest solution might be to
introduce some function in libi86
to restore all interrupt vectors to
their original values.

**Comment by stsp** [comment]
Also with what lib should I link
to avoid this:
`function main: error: undefined reference to 'basename'`?
Currently I simply implemented
`basename()` by hands.

**Comment by stsp** [comment]
As for what dpmi funcs I currently
call by hands: 0xa, 7, 8, 9, 0x501.
But I am not sure you should
implement dpmi wrappers based
on my "demands". You either have
time to implement all, or not. :)

**Comment by stsp** [comment]
> The simplest solution might be to

Actually I guess this is where -mdpmi
should be different. Can -mdpmi (or
-mdpmi32) be not touching the interrupt
vectors, otherwise doing the same as
-mdosx?

**Comment by tkchia** [comment]
Hello @stsp,

> Now I do not do this, and it appears cw32 doesn't support 32bit file I/O (when int21h is called with size in ECX rather than in CX).

That is indeed a weird issue.  The CauseWay code is unfortunately not as rigorous as I had hoped it would be, and the logic it uses to decide whether operands should be 16-bit or 32-bit is confusing in some places (and probably wrong?). :neutral_face: 

Meanwhile, as a workaround, you can try to call the DOS/4G installation check function (`int 0x21`, `ax` = `0xff00`, `dx` = `0x0078`), just before transitioning to 32-bit code.  CauseWay recognizes this call and will basically switch itself to full-fledged 32-bit mode.
```
--------E-21FF00DX0078-----------------------
INT 21 - Rational Systems DOS/4G - INSTALLATION CHECK
	AX = FF00h
	DX = 0078h
Return: AL <> 00h if installed
	    GS = segment of kernel if nonzero
SeeAlso: INT 15/AX=BF02h
```

I will also look at what else I can do on my end.

Thank you!

**Comment by stsp** [comment]
> just before transitioning to 32-bit code.

I use prefixes to put length to ecx,
so this all is before the transition to
32bit code.
I think the simple solution is to make
-mdpmi to not alter intvectors. In that
case cw32 would be used in -mdpmi
mode just as a loader, and the prog
should fully rely only on an existing
dpmi server.

**Comment by tkchia** [comment]
Hello @stsp,

I think you are trying too hard to twist `newlib-ia16` into doing what it is not really meant to do in the first place.  If you do not like the C library getting in the way, perhaps you should be writing your loader in assembly from scratch.

Thank you!

**Comment by stsp** [comment]
In that particular case the newlib-ia16
is not involved. I am calling int21 from
an inline asm. And from that perspective
-mdosx and -mdpmi should behave
differently: either dos extender handles
the call, or the dpmi server.

**Comment by stsp** [comment]
If newlib-ia16 could do long reads/writes
using the far pointer, that would of course
be even better!

**Comment by tkchia** [comment]
Hello @stsp,

Sorry, no, I do _not_ feel like writing 2 different sets of headers and libraries with different sets of internal workings, just because someone might want to mess around with the internal workings (even though they are, like, internal).

`gcc-ia16` and `libi86` already have lots of multilib combinations that I need to test, which is already enough of a nightmare, without adding _yet_ another multilib combination into the mix.

Anyway, perhaps if you explain more clearly what exactly, _at a high level_, you are trying to do, then maybe together we can more fruitfully figure out how to achieve what you want.  Otherwise, no.

Thank you!

**Comment by stsp** [comment]
Large file read (or write) using
the far pointer to the buffer.
This is all I need, and 32bit
dos extenders usually allow to
do this. If yours doesn't - adding
such functionality to the lib is
all I need.

**Comment by tkchia** [comment]
@stsp : then maybe you should be using a 32-bit toochain right from the outset.  `gcc-ia16` targets 16-bit environments.  It is right there on the tin.

**Comment by stsp** [comment]
But it supports far pointers, doesn't it? :)

**Comment by tkchia** [comment]
@stsp : how about this, use either Open Watcom, _or_ use (say) DJGPP and find a way to map 16:32 segment:offset far pointers to flat pointers.  I am not convinced you _absolutely_ _totally_ need to work with 16:32 far pointers.  It should always be possible to map such a far pointer to a good old 32-bit flat address.  Thank you!

**Comment by tkchia** [comment]
@stsp : again, it helps a lot if you can sketch out _at a high level_ (N.B.) what you are trying to do.  Describe the whole thing, start at the beginning, and end at the end.  Which you have consistently refrained from doing, for some reason.

**Comment by stsp** [comment]
Then what do you mean by high-level?
I need to read the file larger than 64Kb,
this is the high-level description, isn't it?
Maybe its possible to read it using the
near pointer first, and then memcpy to
where I need it?

**Comment by tkchia** [comment]
Hello @stsp,

High-level as in, like, a bird's eye view of the whole thing you are trying to do.  Something like, "I want to write a program that can load a 32-bit COFF program into memory and run it, and can also load and run 16-bit Phar Lap program under 16-bit DPMI", etc.

Never mind what you "believe" your program will look like; just say what you want it to do.  This is more fruitful.

Thank you!

**Comment by stsp** [comment]
Yes, it currently loads a coff image
into a large memory buffer addressed
via the far pointer, under the 32bit dpmi.
Nothing about 16bit dpmi is planned
but the code segment is OK to be 16bit.

**Comment by tkchia** [comment]
Hello @stsp,

Then I am not sure why you might need `gcc-ia16` for this &mdash; perhaps you can explain further.  If I were doing this I would probably write the whole thing as a `.com` program in `nasm` from scratch (?).  Thank you!

**Comment by stsp** [comment]
https://github.com/stsp/djstub
The program is here, and works well.
I only wanted to avoid the nasty
DPMI hack of switching to 32bit.

**Comment by tkchia** [comment]
Hello @stsp,

Hmm... what you _probably_ can use is some sort of "freestanding" environment which does not rely on a full-fledged hosted C environment or even a full-fledged DOS extender.

For comparison, check out [UPX](https://github.com/upx/upx)'s decompression stubs.  These are compiled with `-nostdinc`, and generally do not have a `main (`...`)` function.

The `gcc-ia16` toolchain currently has a `-ffreestanding -mprotected-mode` multilib setting &mdash; this is potentially useful for your purposes, but it is still very much untested.  Maybe let me fork your `djstub` project and see if I can work something out.

Thank you!

**Comment by stsp** [comment]
> hosted C environment or even a full-fledged DOS extender.

Yes, I exactly do not want to rely
on a DOS extender. So -ffreestanding
or -mdpmi or whatever that allows to
work with the dpmi server directly, would
do. But I wonder why adding the large
files support is such a bad idea...

**Comment by stsp** [comment]
> files support is such a bad idea...

I mean to libi86, so that I don't even
have to use any tricks. Its not a 32bit-specific
feature.

**Comment by tkchia** [comment]
Hello @stsp,

> Maybe let me fork your `djstub` project and see if I can work something out.

Actually, let me see first if I can build DJ Delorie's original `djasm` as a cross-assembler.  Thank you!

**Comment by stsp** [comment]
>  Maybe let me fork your djstub project and see if I can work something out.

I pushed the -mdosx32 support there
and to dosemu2, so you can now fork
it if you want. But there is still the hack
to shut down cw32, its in `dpmi_init()`
as before.

**Comment by tkchia** [comment]
Hello @stsp,

> But I wonder why adding the large files support is such a bad idea...

Basically:
  * one does not "just" add large file support without testing (and hopefully _not_ breaking) a lot of things
  * and seriously, you do not really need this specific functionality in this case.

The existing DJGPP stub, anyway, already shows how to read a large chunk of bytes without using a DOS extender.  Namely, split the read into smaller chunks, and go through a transfer buffer.  And it does this all in only 8 KiB of space &mdash; quite a steal.

By the way: I added Ubuntu packages for `djasm` (see https://launchpad.net/~tkchia/+archive/ubuntu/de-rebus).

Thank you!

**Comment by stsp** [comment]
I dont think you can break anything by
adding (even w/o testing) new funcs like
_longfread(), _longfwrite().

Yes, I of course can use fread() and just
read by chunks, but the problem is that
fread() doesnt take far pointer, so I will have
to memcpy() by hands.
So for now I just use the direct call, but its
not what I want to do. Any convenient way
of doing the longread() will suit.

**Comment by stsp** [comment]
Do you have at least farmemcpy()?
That will make the read by chunks at
least asm-less.

**Comment by tkchia** [comment]
Hello @stsp,

I think you use (e.g.)
  * `_DPMIAllocateDOSMemoryBlock (.)` to allocate conventional memory
  * and `_DPMISimulateRealModeInterrupt (`...`)` to do the actual reads &mdash; you will probably need to do this anyway for DPMI hosts which do not pass segment register values.

This should basically do the same thing as what DJ's `stub.asm` does.

> Do you have at least farmemcpy()?

`_fmemcpy` is indeed very much implemented in `libi86`.

Thank you!

**Comment by stsp** [comment]
But why can't I use fread() and then
_memcpy()? Why would I need to mess
with interrupt and realmode buffer?
Doesnt fread() work?

**Comment by tkchia** [comment]
@stsp : Dude, please, just stop.  Right now what you are doing, is to load a 40 KiB DOS extender (plus a C library) just to do something that clearly 8 KiB of machine code could already do in 2002.  Maybe take a step back and try to figure out why exactly you think this is even a good idea.

**Comment by stsp** [comment]
I dont understand, there IS fread() in libi86?
Why shouldnt I use? It doesnt work?
Will check tomorrow.

**Comment by tkchia** [comment]
@stsp : read what I wrote above, again.  `fread` is not magical pixie dust.  Nothing "just works" &mdash; everything requires time and space.  `fread` requires _a lot_ of time and space.  Stop thinking of it as magic.
