### ISSUE TITLE
Can't install gcc-ia16-elf on ubuntu lunar

### ISSUE THREAD

**Issue by stuaxo** [tkchia/gcc-ia16#138]
When I look at the PPA, it looks like gcc-ia16-elf is still there, but when I try to install it (to build dosemu2) it seems to fail -

```shell
$ cat /etc/apt/sources.list.d/tkchia-ubuntu-build-ia16-lunar.list 
deb https://ppa.launchpadcontent.net/tkchia/build-ia16/ubuntu/ lunar main
# deb-src https://ppa.launchpadcontent.net/tkchia/build-ia16/ubuntu/ lunar main
```

I ran `apt update -y` but then this fails:

```shell
$ sudo apt install gcc-ia16-elf libi86-ia16-elf libi86-testsuite-ia16-elf
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gcc-ia16-elf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gcc-ia16-elf' has no installation candidate
E: Unable to locate package libi86-ia16-elf
E: Unable to locate package libi86-testsuite-ia16-elf
```

Am I missing something obvious ?

**Comment by tkchia** [comment]
Hello @stuaxo,

I have not arranged to package up the complete toolchain for Ubuntu Lunar yet.  I hope to do so soon.  Thank you!

**Comment by stuaxo** [comment]
Thanks, that at least makes sense :)

**Comment by tkchia** [comment]
@stuaxo : please try again.  Thank you!

**Comment by stuaxo** [comment]
Apologies for not getting round to testing this - have re-run the install and don't get the error any more.

**Comment by tkchia** [comment]
@stuaxo : thanks for letting me know!
