### ISSUE TITLE
version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by ppsilv** [tkchia/gcc-ia16#155]
Linux used to compile:
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

msgfmt: /home/pdsilva/project/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.74)
make[5]: *** [Makefile:495: de.mo] Error 1
make[5]: Leaving directory '/home/pdsilva/Projects/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3/po'
make[4]: *** [Makefile:508: all-recursive] Error 1
make[4]: Leaving directory '/home/pdsilva/Projects/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3'
make[3]: *** [Makefile:415: all] Error 2
make[3]: Leaving directory '/home/pdsilva/Projects/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3'
make[2]: *** [Makefile:13630: all-stage1-target-libstdc++-v3] Error 2
make[2]: Leaving directory '/home/pdsilva/Projects/gcc-ia16'
make[1]: *** [Makefile:23677: stage1-bubble] Error 2
make[1]: Leaving directory '/home/pdsilva/Projects/gcc-ia16'

The same error happens in tag gcc-ia16-20240218.

I try an update:
pdsilva@latitude:~/project/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs$ sudo apt-get install libstdc++6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
********************************************************
**### libstdc++6 is already the newest version (14.2.0-4ubuntu2~24.04).**
********************************************************
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

Why an older project needs a library that a newer linux does not have?

**Comment by asiekierka** [comment]
> msgfmt: /home/pdsilva/project/gcc-ia16/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.74)

What is your configure command? It appears like you're trying to build gcc-ia16, but not as a cross-compiler, so it tries to use its built-in (outdated, the compiler is based on a 2016 version of GCC) libstdc++ combined with your computer's (much newer) libraries; remember GCC can be compiled to target any architecture, including your own PC.

**Comment by ppsilv** [comment]
Sorry for the incovenience of this issue. I did not know the  https://codeberg.org/tkchia/build-ia16/  repo, google never said me.
Now I am trying  https://codeberg.org/tkchia/build-ia16/
