### ISSUE TITLE
fatal error: sys/ustat.h: No such file or directory

### ISSUE THREAD

**Issue by ppsilv** [tkchia/gcc-ia16#156]
Linux used to compile:
Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble

make "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CFLAGS=-g -O2" "CXXFLAGS=-g -O2 -D_GNU_SOURCE" "CFLAGS_FOR_BUILD=-g -O2" "CFLAGS_FOR_TARGET=-g -O2" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=" "LIBCFLAGS=-g -O2" "LIBCFLAGS_FOR_TARGET=-g -O2" "MAKE=make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000 " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/bash" "RUNTESTFLAGS=" "exec_prefix=/home/pdsilva/gcc-ia16_A" "infodir=/home/pdsilva/gcc-ia16_A/share/info" "libdir=/home/pdsilva/gcc-ia16_A/lib" "prefix=/home/pdsilva/gcc-ia16_A" "includedir=/home/pdsilva/gcc-ia16_A/include" "AR=ar" "AS=/home/pdsilva/project/gcc-ia16_A/host-x86_64-pc-linux-gnu/gcc/as" "LD=/home/pdsilva/project/gcc-ia16_A/host-x86_64-pc-linux-gnu/gcc/collect-ld" "LIBCFLAGS=-g -O2" "NM=/home/pdsilva/project/gcc-ia16_A/host-x86_64-pc-linux-gnu/gcc/nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # make
make[3]: Entering directory '/home/pdsilva/Projects/gcc-ia16_A/x86_64-pc-linux-gnu/libcilkrts'
../../.././libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:158:23: fatal error: sys/ustat.h: No such file or directory
 #include <sys/ustat.h>
                       ^
compilation terminated.

**Comment by asiekierka** [comment]
`libcilkrts` is not built as part of a standard gcc-ia16 build; it appears you're trying to build it as an x86_64 compiler, rather than a cross-compiler.

**Comment by ppsilv** [comment]
Sorry for the incovenience of this issue. I did not know the  https://codeberg.org/tkchia/build-ia16/  repo, google never said me.
Now I am trying  https://codeberg.org/tkchia/build-ia16/
