### ISSUE TITLE
error: multiple definition of ‘enum fsconfig_command’

### ISSUE THREAD

**Issue by ppsilv** [tkchia/gcc-ia16#157]
Linux used to compile:
Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble

/usr/include/linux/mount.h:96:6: error: multiple definition of ‘enum fsconfig_command’
 enum fsconfig_command {

**Comment by asiekierka** [comment]
Insufficient data to figure out where the issue occured.

**Comment by ppsilv** [comment]
Sorry for the incovenience of this issue. I did not know the  https://codeberg.org/tkchia/build-ia16/  repo, google never said me.
Now I am trying  https://codeberg.org/tkchia/build-ia16/
