### ISSUE TITLE
error: redefinition of ‘struct mount_attr’

### ISSUE THREAD

**Issue by ppsilv** [tkchia/gcc-ia16#158]
Linux used to compile:
Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble

In file included from /usr/include/linux/fs.h:19:0,
                 from ../../.././libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:70:
/usr/include/linux/mount.h:131:8: error: redefinition of ‘struct mount_attr’
 struct mount_attr {

**Comment by asiekierka** [comment]
Insufficient data to figure out where the issue occured.

**Comment by ppsilv** [comment]
Sorry for the incovenience of this issue. I did not know the  https://codeberg.org/tkchia/build-ia16/  repo, google never said me.
Now I am trying  https://codeberg.org/tkchia/build-ia16/
