### ISSUE TITLE
Any chance to package up the ia16 toolchain in an Ubuntu PPA?

### ISSUE THREAD

**Issue by andrewbird** [tkchia/gcc-ia16#17]
Now that FreeDOS has [added](https://github.com/PerditionC/fdkernel/pull/25) your ia16 toolchain as a build method for the kernel, perhaps there's the opportunity to expand its availability via an Ubuntu [PPA](https://launchpad.net/ubuntu/+ppas)? Having the packages built automatically on every repository change using a 'recipe' would allow users to keep up to date with your current code whilst requiring minimal effort on both your part and theirs.

**Comment by tkchia** [comment]
Thank you!  I will look into this.  I am not familiar with creating PPAs yet, so it will probably take a while.

**Comment by zfigura** [comment]
Is there a reason not to simply upstream the toolchain to GCC?

**Comment by andrewbird** [comment]
Upstreaming would the ultimate goal, though I suspect that could take some time to happen and of course to filter down to distros would take much longer.

**Comment by zfigura** [comment]
Makes sense, thanks.

**Comment by tkchia** [comment]
Well, after a few days of trial and error, I have finally created an Ubuntu source package for Jenner's [Binutils](https://github.com/crtc-demos/binutils-ia16) IA-16 port, and uploaded it to [my PPA](https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16). :-)

I hope to also set up source packages for Newlib, GCC proper, as well as `libgcc1`, though I expect the build dependencies between these to be a bit trickier to untangle (e.g. in `build.sh` Newlib depends on stage 1 GCC, and stage 2 GCC depends on Newlib).

Also, I have not yet got Launchpad to create source packages using a "recipe", so I will be looking into this.

Thank you!

**Comment by andrewbird** [comment]
Thank you, that's great!

**Comment by tkchia** [comment]
My [PPA](https://launchpad.net/%7Etkchia/+archive/ubuntu/build-ia16) is now up and ready. :)

**Comment by tkchia** [comment]
For the curious, the code for creating the source packages is in the [`build-ia16`](https://github.com/tkchia/build-ia16/) component, specifically the script `redist-ppa.sh` and the files in `ppa-pkging/`.  I currently run the script on my PC to create the source packages, but (as stated) I hope to get Launchpad to help do this work.

Thank you!

**Comment by andrewbird** [comment]
I added the ppa, installed the i386 version and then compiled freedos successfully.
Thanks, that's great, it's just what I needed.

**Comment by tkchia** [comment]
Glad to hear that.  Thank you!
