### ISSUE TITLE
Far functions with data and stack separate (was: Need sane way to define and handle far functions (callable from outside code))

### ISSUE THREAD

**Issue by tkchia** [tkchia/gcc-ia16#19]
There is currently no support for far functions in `gcc-ia16`, which is a rather bad thing, because [the FreeDOS kernel](https://github.com/bartoldeman/fdkernel/tree/ia16-elf-gcc) relies a lot on far functions to work.

To properly support far functions, I see two things that need to be done:

  * First is _a simple way to specify that a function is far_, i.e. returns with `lret` rather than a near `ret`.  This can be done by inventing a new function attribute (something like `__attribute__ ((callfar))`).  If another C routine (in the same program) calls this function, GCC should arrange to add a `pushw %cs` before a near `call` instruction.
  * The second thing to do is trickier: _a way for the far function to address data items in the program's data space_ (`.rodata`, `.data`, `.bss`).  Currently GCC assumes that `%ss` points to this program data space, but this is likely not the case if the far function is called from outside code.  My current idea to "work around" this is to arrange for a far function to "switch" to a designated stack area in `.bss`, but this has its own share of complexities...

**Comment by zfigura** [comment]
With regard to the first question, why not use the same attribute as you're already using, i.e. __far?

With regard to the second question, why not use %ds to address far data? That's how it's supposed to work. Trying to shuffle ds -> ss -> separate stack space, just so you have two segment registers free for allocation, hardly seems worth the effort. Unless of course I'm misunderstanding the question.

(A better idea, if we're that concerned about playing hot-potato with %es, would probably be to add support for %fs and %gs.)

**Comment by tkchia** [comment]
Hello @obsequiousnewt,

> With regard to the first question, why not use the same attribute as you're already using, i.e. __far?

Thanks for your suggestions!  The "why nots" are mainly due to some assumptions and limitations in GCC's middle-end architecture --- though they are by no means showstoppers.

Currently `__far` support is based on GCC's Named Address Spaces, which in turn follows the [N1275](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1275.pdf) C99 extension proposal, so it has a well-defined syntax which is a bit [incompatible](https://github.com/tkchia/gcc-ia16/issues/11) with classical DOS compiler syntax.  Thus

> `int __far foo (unsigned x);`

is currently interpreted as saying that `foo (.)` is a normal (near) function which returns a value of type `int __far` --- which as a return type is no different from `int`.

(However, I suspect that it _might_ be feasible to make the back-end somehow mark a function as far if it sees a far return type, so that the above syntax will work --- I might try this.)

> With regard to the second question, why not use %ds to address far data?

Given, say, this routine (from FreeDOS's `kernel/dsk.c`)
```c
COUNT ASMCFUNC FAR blk_driver(rqptr rp, ...)
{
  if (rp->r_unit >= blk_dev.dh_name[0] && rp->r_command != C_INIT)
    return failure(E_UNIT);
    ...
}
```
--- the problem is that, without moving `%ss:%sp` into the program's own data segment, I will need to have a way to tell GCC that automatic variables (e.g. `rp`) can be addressed via `%ss`, while static variables (e.g. `blk_dev`) need to be addressed in a different way (via `%ds` or `%es` after setting them up properly).

Unfortunately, GCC now assumes that the generic address space (i.e. the space containing non-`__far`-qualified data items) is one single flat space, so `rp` and `blk_dev` can both be accessed in the same manner, even though this is likely not true here.

Thank you!

**Comment by tkchia** [comment]
Hmm, reading through the FreeDOS kernel code, it seems that `kernel/io.asm` already makes `%ss` point to FreeDOS's data segment before invoking `blk_driver (.)`, so perhaps the second problem I stated is not as urgent to solve as I had earlier thought.

**Comment by zfigura** [comment]
Ah, I see, I did not correctly understand the reason for the shuffling. That said,

> --- the problem is that, without moving %ss:%sp into the program's own data segment, I will need to have a way to tell GCC that automatic variables (e.g. rp) can be addressed via %ss, while static variables (e.g. blk_dev) need to be addressed in a different way (via %ds or %es after setting them up properly).

Is this not possible? It seems to me that this is the only scalable solution. Trying to switch stacks won't work if there's not enough space available. In particular this solution can't work at all in protected mode.

**Comment by bartoldeman** [comment]
thanks! Quick testing shows that it does the job (including the "push cs" when calling one).

Indeed the freedos kernel assembly assumes small model which means DS=SS=DGROUP.
OW has the -zu switch which can float SS but then still DS=DGROUP.

I believe that once you go into compact, large and huge memory models, there is one DS per file. So then all non-static functions in the file set DS="FILE_DGROUP" at the beginning, and SS points to the single stack. But to properly support (beyond's fdkernel's limited linker script magic, a miracle that that works!) that you need OMF and relocations. Perhaps a nasm backend as in DJGPP's ancient port http://www.delorie.com/djgpp/16bit/ was not such a bad idea :)

**Comment by zfigura** [comment]
Large model supports multiple data segments. (So does compact model.)

It would be good to have large model support in GCC. Obviously there is no OMF or NE support in binutils, but I am working on the latter. I'd offer to help with GCC as well, but I know absolutely nothing about how GCC works.

**Comment by tkchia** [comment]
Hello @bartoldeman,

> thanks! Quick testing shows that it does the job (including the "push cs" when calling one).

That is cool. :)  I will try to do some further testing to make sure that calling a far function works reliably, then see where to go from there.

> Indeed the freedos kernel assembly assumes small model which means DS=SS=DGROUP.
> OW has the -zu switch which can float SS but then still DS=DGROUP.

The `-zu` switch is interesting.  Out of curiosity, I decided to try writing a C module which mixes static variables and stack variables and see how Turbo C (2.01) and Open Watcom (2.0 β 2017/6/17) would react:
```c
extern int wut (long *), wot (long);

static long static_var_1, static_var_2;

int foo (int x, long auto_var_1, long auto_var_2)
{
  return wut (x ? &auto_var_1 : &static_var_1)
         + wot (x ? auto_var_2 : static_var_2);
}

int far bar (int x, long auto_var_1, long auto_var_2)
{
  return wut (x ? &auto_var_1 : &static_var_1)
         + wot (x ? auto_var_2 : static_var_2);
}

int interrupt qux (int x, long auto_var_1, long auto_var_2)
{
  return wut (x ? &auto_var_1 : &static_var_1)
         + wot (x ? auto_var_2 : static_var_2);
}

int far quux (int far x, long far auto_var_1, long far auto_var_2)
{
  return wut (x ? &auto_var_1 : &static_var_1)
         + wot (x ? auto_var_2 : static_var_2);
}
```
I found that Turbo C (`tcc -S -w test.c`) happily compiled the whole file --- and assumed that all the variables would be in the same segment (!).  Watcom C (`wcc -ms -os test.c`) did complain about the mixing, but only for the last two routines:
```
Open Watcom C x86 16-bit Optimizing Compiler
Version 2.0 beta Jun 17 2017 16:17:56 (64-bit)
Copyright (c) 2002-2017 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
test.c(19): Warning! W112: Parameter 1: Pointer truncated
test.c(19): Note! N2003: source conversion type is 'long __far *'
test.c(19): Note! N2004: target conversion type is 'long *'
test.c(19): Note! N2002: 'wut' defined in: test.c(1)
test.c(25): Warning! W112: Parameter 1: Pointer truncated
test.c(25): Note! N2003: source conversion type is 'long __far *'
test.c(25): Note! N2004: target conversion type is 'long *'
test.c(25): Note! N2002: 'wut' defined in: test.c(1)
test.c: 27 lines, 2 warnings, 0 errors
Code size: 235
```
(Only with `-zu` did Open Watcom did complain about all the routines.)

So perhaps I had been overthinking my second problem, and assuming `%ds` == `%ss` == `.data` --- even for functions marked `__far` --- is not that far from common practice back in the day.

(Still, for the sake of correctness, I think it would be nice for GCC to be able to allow `%ss` to "float" outside `.data` in a well-defined way, though I am not sure how.)

Thank you!

**Comment by tkchia** [comment]
Hello @obsequiousnewt ,

> Obviously there is no OMF or NE support in binutils, but I am working on the latter.

Thanks!  I look forward to trying it out.

> I'd offer to help with GCC as well, but I know absolutely nothing about how GCC works.

In case this is something you are interested in: I started learning about GCC internals through the `gccint` info page --- which is [online](https://gcc.gnu.org/onlinedocs/gccint/) (and, alternatively, also available on Ubuntu through the `gcc-doc` package).  Most of the work to port GCC to IA-16 has been in the "Machine Description" portion, which is where the target-dependent back-end is.

(On Mr. Jenner's advice, I had also submitted a copyright assignment to FSF for my GCC patches, so that there would be no legal issues in getting them all the way upstream.)

Thank you!

**Comment by zfigura** [comment]
So I finally went to check MSVC. MSVC has two separate options, one for memory model and one for ss/ds setup; the latter has "SS == DS", "SS != DS, DS loaded on function entry", and "SS != DS, DS NOT loaded on function entry". The first one is default. The second one is what I usually see in disassembled 16-bit code that I work with, which comprises a 'push ds; mov ax; <relocation>; mov ds, ax' on function entry and 'pop ds' on exit.

Interestingly enough, the third option just assumes ds will be correct even for far functions. I'm not sure under what basis...

MSVC doesn't use ds as a general segment register; it just uses es for whatever it has to. This, again, matches real code I've seen. Not that we have to follow this, of course.

**Comment by bartoldeman** [comment]
The change that caused ds to float in ia16-elf-gcc only caused me a few issues with inline assembly that would not normally happen with DOS compilers (e.g. if you call DOS/BIOS interrupts that need ds:dx using asm). Once I figured that out it was easy to fix though (or in complex cases, just use external assembly instead of fighting with the syntax).

**Comment by bartoldeman** [comment]
@tkchia did you also think of far function pointers such as `int (far *f)(void);`

**Comment by tkchia** [comment]
Hello @bartoldeman ,

> did you also think of far function pointers such as `int (far *f)(void);`

Yes, implementing far function pointers is something that I have been thinking about a bit.  This will probably require some (intrusive) changes to GCC's machine-independent middle-end, in order to

  * implement a semi-sane syntax for expressing far function pointers without lots of `typedef`-ing (maybe something like `int (*f) (void) __far`), and to
  * remove the assumption that a function is always in the default (near) address space; and
  * if possible, implement a way to automagically transform `int __far (*) (void)` into `int (*) (void) __far`.

Thank you!

**Comment by zfigura** [comment]
On MSVC, if I recall correctly, it looks something like "int _far (_far myfunc) (...)", where the first _far specifies a far pointer and the second _far specifies that the function is far.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

With [my](https://github.com/tkchia/gcc-ia16/commit/f675fd2ec194bba21dc6482f1f7da7235c77cbc6) [more](https://github.com/tkchia/gcc-ia16/commit/3482578584b919d9d43ddf61bc24127b14894b8b) [recent](https://github.com/tkchia/gcc-ia16/commit/2e2a030010629b934d51b248bf40bde2984f11dd) [commits](https://github.com/tkchia/gcc-ia16/commit/834591a9610bf9cb124a2772e7f05d46221dd3b9), I have got GCC to start grokking far function pointers, at least at the semantic level.  Thus for example
```c
typedef int func_t (long);
typedef func_t __far far_func_t;

int bar (far_func_t *foo, long x)
{
  return foo (x);
}
```
now correctly outputs an `lcall` instruction with a pointer in memory as an operand.

> The change that caused ds to float in ia16-elf-gcc only caused me a few issues with inline assembly that would not normally happen with DOS compilers

Ugh --- sorry for that. :-|

I had to work around this issue myself in my [PDCurses port to `ia16-elf-gcc`](https://github.com/tkchia/PDCurses), and the workaround still looks rather stupid --- to get the data segment value, the code casts a near pointer to a far pointer and applies the equivalent of `FP_SEG (.)` on it.

Perhaps I (or someone who is not me) should invent a few `__builtin_`... `()` functions in GCC to return the code segment and data segment values, which should then solve such issues more elegantly.

Hello @zfigura ,

Sorry if it is a silly question... but which version(s) of MSVC are you referring to, and how might I obtain them?

Thank you!

**Comment by bartoldeman** [comment]
I have this example:
https://github.com/bartoldeman/freecom/blob/b323c976d0c95e0b5c004a8337141b8c2b6132fd/lib/exec.c

```
static char *parsfnm(const char *cmdline, struct fcb far *fcbptr, int option)
{
  char *ret;
  unsigned char opt = option;
  asm volatile("int $0x21" :
      "=S"(ret), "+Ral"(opt) :
      "Rah"((unsigned char)0x29), "e"(FP_SEG(fcbptr)), "D"(FP_OFF(fcbptr)),
      "Rds"(FP_SEG(cmdline)), "0"(cmdline) :
      "cc", "memory");
  return opt == 0xff ? NULL : ret;
}
```

indeed FP_SEG casts to a far pointer already here. It's easy to write static inline assembly functions that obtain ds and friends too.

**Comment by zfigura** [comment]
Visual C++ 2.0. It's available on WinWorld.

**Comment by tkchia** [comment]
Hello @bartoldeman, hello @zfigura, 

Sorry again for the delayed reply... 

> So then all non-static functions in the file set DS="FILE_DGROUP" at the beginning, and SS points to the single stack. But to properly support (beyond's fdkernel's limited linker script magic, a miracle that that works!) that you need OMF and relocations.

For MZ relocation support, there _might_ be a way to do it under the current "ELF input↝binary output" setup (without OMF) -- though it still falls short of full-blown large model support. 

In Mr. Jenner's `binutils-ia16` patches, he made provisions for -- but did not implement -- a new `R_386_SEGMENT` relocation type. The intent is likely so that if one writes, say, 
````
movw $errno@SEGMENT, %ax
movw %ax, %ds
````
this will create an `R_386_SEGMENT` relocation entry in the ELF `.o` file, which should fill in the first 16-bit operand properly _and_ make an MZ relocation appear in the final `.exe`.

Now,  in my `newlib-ia16` patches, I had already implemented small model support by (mis)using Binutils's ability to [separate load memory addresses (LMAs) from virtual memory addresses (VMAs)](https://sourceware.org/binutils/docs-2.29/ld/Basic-Script-Concepts.html). So...

**Comment by tkchia** [comment]
...to implement the first part of `R_386_SEGMENT`, one way is to subtract the LMA of (in this case) `errno`'s section from its VMA (also taking into account the `.exe` header's LMA, if any).

Last week I tried [implementing](https://github.com/tkchia/binutils-ia16/commit/fbbd0153bbb109fca5f3f85173f619be2de1bd3a) this first half in `binutils-ia16`, in the form of a new ELF relocation type which I call `R_386_RELSEG16`. It seems to be working.

Thank you!

**Comment by zfigura** [comment]
It took me a while to come back to this, but: I'm still bothered by the syntactic incompatibility between this __far and the classical __far used in old 16-bit source. I'm not particularly well-versed in GCC syntactic details, but is there any reason we can't use a type attribute rather than a function attribute?

**Comment by tkchia** [comment]
Hello @zfigura ,

> It took me a while to come back to this, but: I'm still bothered by the syntactic incompatibility between this __far and the classical __far used in old 16-bit source. I'm not particularly well-versed in GCC syntactic details, but is there any reason we can't use a type attribute rather than a function attribute?

Well, yes and no.  Right now, the problem is not because of GCC _per se_.  Rather it is because the FreeDOS kernel currently considers `int __far blk_driver (`...`);` as declaring a _near_ function, specifically when it is being built with GCC.  Changing this construct's default meaning on the GCC side will most likely break compatibility with this existing code...

I have actually implemented the `int __far` ... syntax for far functions, but it is not enabled by default (there is a `-mfar-function-if-far-return-type` option which will turn it on).  In any case, even with this option, the syntax will still not be completely compatible with the classical `__far `syntax: function pointers must be defined as, say, `int __far (*) ();` rather than `int (__far *) ();`

Actually, I am still not very sure if this is a good way to deal with this issue.

Thank you!

**Comment by stsp** [comment]
> FreeDOS kernel currently considers int __far blk_driver (...); as declaring a near function

I may be completely out of context here
(never used gcc-ia16 yet), but I just checked
with gdb and can see that `blk_driver()` is
called from `io.asm:blk_entry` with this code:
`call    far [cs:bx+2]`. So it sounds very strange
to me that you call it a `near` function.
But again, I am out of the gcc-ia16 context here.

**Comment by zfigura** [comment]
I'm also not sure what an `int __far` is. Do you mean `int __far *`?

**Comment by stsp** [comment]
`COUNT ASMCFUNC FAR blk_driver(rqptr rp);`
AFAIK `FAR` here means exactly that the
function should return with `retf`.

**Comment by stsp** [comment]
Hmm, I think there is indeed a sucker here in FreeDOS:
`void FAR *DetectXMSDriver(VOID)` - near function that
returns far ptr. Seems to be just one function like this.
I use my own (clang-based) compiler for building freedos,
and I think it has the similar problem... So for my
compiler I'll implement the following syntax:
`void FAR * FAR DetectXMSDriver(VOID)` will mean
the far function, and `void FAR *DetectXMSDriver(VOID)`
will mean near function (currently mistakenly treated
as far).

**Comment by tkchia** [comment]
Hello @stsp , hello @zfigura ,

> can see that `blk_driver()` is called from `io.asm:blk_entry` with this code: `call far [cs:bx+2]`. So it sounds very strange to me that you call it a `near` function.

There is actually a hack --- I believe @bartoldeman added it --- where `blk_entry` actually calls a far _wrapper function_ `blk_driver_wrap` (in `kernel.asm`), and the wrapper function calls the actual `blk_driver (`...`)` as a _near_ function.

(You should be able to see this if you compile the FreeDOS kernel sources using `make COMPILER=gcc all`, and then use `ia16-elf-objdump` to dump the intermediate `.obj` files.)

Anyway, since my `gcc-ia16` fork (from 18 Feb onwards) does actually have the proper support for treating `int __far blk_driver (`...`);` as a far function declaration, perhaps I can try to change things on the FreeDOS end, to remove the need for this hack.

> AFAIK `FAR` here means exactly that the function should return with `retf`.

Well... long story short, as things stand, `gcc-ia16` ignores the `__far` in `int __far blk_driver (`...`);` by default.  (But that may change.)

Thank you!

**Comment by zfigura** [comment]
No, that makes sense:
`int FAR *func1(void);` is a near function that returns a long pointer to an integer, and
`int FAR func2(void);` is a far function that returns an integer, and
`int FAR * FAR func3(void);` is a far function that returns a far pointer to an integer. You could also do
`int * FAR func4(void);` which would be a far function that returns a _near_ pointer to an integer, but I have no idea what use that would be.

**Comment by bartoldeman** [comment]
Yes, all those changes are workarounds for older functions of ia16-elf-gcc. I did not get around to changing it in the FD kernel yet, but since ia16-elf-gcc is still rapidly changing there is no need to worry much about backwards compatibility here. I can have a look at fixing it myself but won't have time this week.

**Comment by stsp** [comment]
> int * FAR *func3(void); is a far function that returns a far pointer to an integer.

Two asterisks? Are you sure?
I would write this as `int FAR * FAR func3(void);`

> int * FAR func3(void); which would be a far function
> that returns a near pointer to an integer, but I have no idea what use that would be.

I think this makes the perfect sense and use for the
"medium" memory model, which is very wide-spread
in DOS software.

**Comment by stsp** [comment]
> Well... long story short, as things stand, gcc-ia16 ignores the __far
> in int __far blk_driver (...); by default. (But that may change.)

How do you handle `void FAR *DetectXMSDriver(VOID)` right now?

**Comment by tkchia** [comment]
Hello @bartoldeman ,

Thank you!

Hello @stsp ,

> How do you handle `void FAR *DetectXMSDriver(VOID)` right now?

Following [N1275](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1275.pdf), so the prototype has the expected meaning (a near function returning a pointer to a far memory area).  `gcc-ia16` treats the `__far` keyword syntactically similar to `const`, `volatile`, `_Atomic`, etc.  `void __far` means that the `__far` qualifier applies to the `void` thing (and only the `void` thing).

**Comment by tkchia** [comment]
(According to the current default GCC rules (without `-mfar-function-if-far-return-type`, that is), `int __far func2 (void);` means that the `__far` applies only to the `int` thing (!), and thus has no effect.)

**Comment by stsp** [comment]
> Following N1275, so the prototype has the expected meaning (a near function returning
> a pointer to a far 

And with `-mfar-function-if-far-return-type` what will happen?
Will it suddenly became far function?

> (According to the current default GCC rules (without -mfar-function-if-far-return-type, that is),
> int __far func2 (void); means that the __far applies only to the int thing (!), and thus has no effect.)

I am confused.
So without `-mfar-function-if-far-return-type` this `__far`
is ignored. And with `-mfar-function-if-far-return-type` it
will work as expected only because it is ignored for int.
So am I right that:
1. For `void FAR *DetectXMSDriver(VOID)` the `-mfar-function-if-far-return-type`
will breaak things
2. For `int __far func2 (void);` the _missing_ `-mfar-function-if-far-return-type`
will break things
3. For `void __far * __far foo(void);` the second `__far` is ignored?

If the above are true, then there seem to be no
any valid-for-everything configuration.

**Comment by zfigura** [comment]
>> int * FAR *func3(void); is a far function that returns a far pointer to an integer.
>
> Two asterisks? Are you sure?
> I would write this as int FAR * FAR func3(void);

Er, yes, sorry, I fat-fingered that. I meant to write what you wrote but mentally swapped `*` and `FAR`.

**Comment by tkchia** [comment]
Hello @stsp ,

> 1.  For `void FAR *DetectXMSDriver(VOID)` the `-mfar-function-if-far-return-type` will break things
> 2. For `int __far func2 (void);` the _missing_ `-mfar-function-if-far-return-type` will break things
> 3. For `void __far * __far foo(void);` the second `__far` is ignored?

1. No, no, no! ☺  `void __far *DetectXMSDriver (void);` is always a near function --- with or without the option.  (Think of `__far` as modifying the `void`, and not the `*`, and not `DetectXMSDriver`.  The way this works is similar to other qualifiers like `const` --- `const char *` (or `char const *`) means a (non-constant) pointer to constant characters, `volatile char * const` means a constant pointer to non-constant but volatile characters, etc.).
2. Yes --- it will be considered a near function in that case.
3. `void __far * __far foo (void);` always returns a far pointer (in `%dx:%ax`).  The function _itself_ is a far function --- callable by `lcall`, returns with `lret` --- if and only if `-mfar-function-if-far-return-type` is used.

Once FreeDOS has been modified to _not_ depend on `int __far f (void);` being a near function, I intend to make `-mfar-function-if-far-return-type` the default setting.

Thank you!

**Comment by stsp** [comment]
> No, no, no! ☺ void __far *DetectXMSDriver (void); is always a near function ---
> with or without the option. (Think of __far as modifying the void, and not the *,
> and not DetectXMSDriver.

But then why it returns a far ptr to void, if `__far` only
applies to `void`, and is therefore ignored?

**Comment by tkchia** [comment]
Hello @stsp ,

> But then why it returns a far ptr to void, if `__far` only applies to `void`, and is therefore ignored?

It is not ignored.  `__far` in `void __far *` is not a property of the pointer, but a property of the pointed-to area.  The pointer just happens to need to be of a different size, in order to correctly point to the `__far` area.

**Comment by stsp** [comment]
What would be the difference between `void __far *`, `void * __far`
and `void __far * __far`?

**Comment by stsp** [comment]
Or are these differences only internal
to gcc unless `-mfar-function-if-far-return-type`
is used, with which the difference became
visible to the user?

**Comment by tkchia** [comment]
Hello @stsp ,

> What would be the difference between `void __far *`, `void * __far`
and `void __far * __far`?

Thank you!  You can try compiling these variable definitions to assembly (this requires the small memory model `-mcmodel=small`):
```c
void __far *p1;
void * __far p2;
void __far * __far p3;
```
This yields
```asm
        .arch i8086,jumps
        .code16
        .att_syntax prefix
#NO_APP
        .global p3
        .section        .fardata.p3.07172,"aw",@progbits
        .p2align        1
        .type   p3, @object
        .size   p3, 4
p3:
        .skip   4,0
        .global p2
        .section        .fardata.p2.32406,"aw",@progbits
        .p2align        1
        .type   p2, @object
        .size   p2, 2
p2:
        .skip   2,0
        .comm   p1,4,2
        .ident  "GCC: (GNU) 6.3.0"
```
So:
  * `p1` is a 32-bit pointer which resides in the near `.data` (or `.bss`) segment;
  * `p2` is a 16-bit pointer which resides _outside_ the near data segment (but points back to the near segment);
  * `p3` is a 32-bit pointer which resides outside the near data segment and also points outside the near segment.

For functions, similar rules apply.  Except, one cannot really talk about a function's return value "residing in the near segment" or "residing in the far segment" (on the x86, return values normally go in registers anyway...), so this is exactly where things get a bit hairy.

Thank you!

**Comment by stsp** [comment]
Ahh, I finally understand, thanks!
I think I was confused by this:
`Think of __far as modifying the void, and not the *, and not DetectXMSDriver.`
which implies there are 3 targets to modify.
But I think there are only 2: pointer (a symbol)
and pointee (a memory space), but not the asterisk
itself, as your quote above implied. Is this correct?

Can we simply consider the second `__far` that
modifies the symbol, to just modify the function
itself, as it does for pointer symbol or for any
other symbol like `extern int __far a;`?
If `__far` here applies to symbol `a`, then why in
`extern int __far a(void);` it would apply to the
return value of `a`, and not to `a` itself?
(I mean when the option is not specified)

**Comment by tkchia** [comment]
Hello @stsp ,

> Can we simply consider the second `__far` that modifies the symbol ... as it does for pointer symbol or for any other symbol like `extern int __far a;`?

_Actually_ I would say that in `extern int __far a;`, the `__far` modifies the type, i.e. `int` (and the fully-qualified type, i.e. `int __far`, _then_ affects how `a` is stored).

Thank you!

**Comment by stsp** [comment]
OK, `extern int * __far a;` then.
Does it affect only `a`?

**Comment by tkchia** [comment]
Hello @stsp ,

The `__far` in `extern int * __far a;` affects `a` _by way of_ affecting the pointer type.  You can also write
```
typedef int * __far fpi_t;
extern fpi_t a;
```
which will mean the same thing.

Basically, GCC implements `__far` as a _type-qualifier_ from the view of [C11 syntax](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf).   (In contrast, [Watcom C](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wic/c/cparse.y?utf8=%E2%9C%93#L710) parses `far` as a different kind of token, a _mem-modifier_, which is not in GCC.)

Thank you!

**Comment by tkchia** [comment]
Hello @bartoldeman ,

I have [updated](https://github.com/tkchia/fdkernel/commit/49d1939ed7e9b95d6b06feeef8cd9bc78c1e582f) my FreeDOS kernel fork to get it to use `-mfar-function-if-far-return-type`, and thus treat `int __far blk_driver (`...`);` as a far function.  In the process I also had to add a hack to GCC so that programs can take the `FP_OFF (.)` of far functions from within static initializers (this is done in [`kernel/main.c`](https://github.com/tkchia/fdkernel/blob/49d1939ed7e9b95d6b06feeef8cd9bc78c1e582f/kernel/main.c#L243)).

Once I have run the regression tests on the updated GCC, I hope to send you the push request for my modifications to `fdkernel`.

Thank you!
