### ISSUE TITLE
All functions called as if cdecl with `-mrtd`

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#20]
In the following:
```
extern char *strdup(const char *);
char *Estrdup(const char * const str)
{
	return strdup(str);
}
```
compiling with `-mrtd -S`, you see a `addw    $2,     %sp` generated that should not be there.
This seems to be a regression in c97e8cc; 95fbd1fdb still works properly.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

Ugh --- I made a mistake while implementing support for `__attribute__ ((stdcall))` and `__attribute__ ((cdecl))`.  Thank you for spotting it!
