### ISSUE TITLE
Initializing far pointer using near pointer.

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#26]
This code typically compiles with DOS compilers but not ia16-elf-gcc:
```
$ cat nearfar.c
extern int i;
int __far *j = &i;
$ ia16-elf-gcc -c nearfar.c
nearfar.c:2:16: error: initializer element is not computable at load time
 int __far *j = &i;
                ^
```
Not sure if this is feasible using GCC?
It can be worked around using explicit segment and offset and a linker symbol (as in the FreeDOS kernel nls.c for nlsPackageHardcoded)..

**Comment by tkchia** [comment]
Hello @bartoldeman ,

Thanks for the report!  Indeed, it seems to be a problem to get (at least this version of) GCC to do address space conversions within static initializers.  I will try to see if there is a reasonably neat way to implement this.

**Comment by JL2210** [comment]
Give this a shot:
```
extern int i;
int __far *j;
j = &i;
```

**Comment by JL2210** [comment]
Does casting the pointer to an `int __far *` work? e.g.
```
$ cat nearfar.c
extern int i;
int __far *j = (int __far *)&i;
```

**Comment by tkchia** [comment]
Hello @bartoldeman,

I have started to implement a `__builtin_ia16_static_far_cast (.)` function which can be used in static initializers to cast near pointers to far pointers.  The usage is like this:
```
extern int i;
int __far *j = __builtin_ia16_static_far_cast (&i);
```

This is still not as neat as simply allowing a direct conversion, but it works, and is (hopefully) not too ugly.

Thank you!
