### ISSUE TITLE
PPA needs packages building for Bionic

### ISSUE THREAD

**Issue by andrewbird** [tkchia/gcc-ia16#27]
Hi there, I upgraded my xenial machine to bionic, but as yet there are no packages in the PPA. Can you add them to the build recipe please?

Thanks

**Comment by tkchia** [comment]
Hello @andrewbird ,

I will work on this.  Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird ,

Packages for Ubuntu Bionic are now available.  Let me know if you have any problems with them.  Thank you!

**Comment by andrewbird** [comment]
Thank you. I didn't get the chance to test, but certainly they were able to be downloaded and installed from the PPA.
