### ISSUE TITLE
regparm

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#29]
Hi,

I saw your regparm changes with interest and noticed the issues with `-Os`. Maybe it is better to backtrack a little and borrow from the regular i386 regparm (as in https://gcc.gnu.org/onlinedocs/gcc-6.4.0/gcc/x86-Function-Attributes.html#x86-Function-Attributes) and exclude bx? Compatibility with OpenWatcom is not very important at all, since the 4 reg calling convention is very specific to that compiler. Other DOS compilers had different regparm conventions (see page 17 here: https://www.agner.org/optimize/calling_conventions.pdf)

Secondly I found out years ago that just using ax, dx, cx can actually produce smaller code with OW (I put a pragma aux in the FD kernel to do just that, i.e. `#pragma aux default parm [ax dx cx] modify [ax dx es fs]`). After all. `bx` is special since it can be used to address memory.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

> Secondly I found out years ago that just using ax, dx, cx can actually produce smaller code with OW (I put a pragma aux in the FD kernel to do just that, i.e. `#pragma aux default parm [ax dx cx] modify [ax dx es fs]`).

Hmm... this is interesting.  Do you happen to have any idea(s) why the code actually ends up smaller?

In any case, since it seems beneficial, I will see if I can implement your suggestion and try excluding `%bx` from the calling convention.  I suspect the result will actually be a bit simpler than what I have now.

(As far as I can tell, the i386 port excludes `%ebx` mainly because it is used in position-independent code (PIC) to point to the global offset table.  Of course, nothing prevents the ia16 port from excluding `%bx` from parameter passing for a different reason...)

Thank you!

**Comment by bartoldeman** [comment]
I don't have the an exact example, but you can easily imagine the called function running out of registers so not needing to put more local variables on the stack: if the function needs to use `bx` for something it may need to push the passed `bx` to the stack any way. You could experiment a little.

In any case obviously it would be very nice if this could be a way to get regparm to work with `-Os`.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

> if the function needs to use `bx` for something it may need to push the passed `bx` to the stack any way. You could experiment a little.

Thanks!  Maybe I will play with Open Watcom's parameter passing a bit (when I have more of this "copious spare time" thing) and see what I can find.

> In any case obviously it would be very nice if this could be a way to get regparm to work with `-Os`.

Well, the issue I found was that `-mregparmcall -Os` sort of barfed when dealing with 64-bit scalars --- and still does not work very well with them, even when I exclude `%bx`.  For example, this routine
```c
unsigned long long frobfrobfrob (unsigned long long x)
{
        return x + 1;
}
```
when compiled with `-mregparmcall -Os` currently yields
```asm
        .global frobfrobfrob
        .type   frobfrobfrob, @function
frobfrobfrob:
        pushw   %si
        pushw   %di
        pushw   %bp
        movw    %sp,    %bp
        subw    $8,     %sp
        movw    %ax,    %si
        movw    8(%bp), %cx
        movw    10(%bp),        %ax
        movw    12(%bp),        %dx
        movw    14(%bp),        %bx
        movw    %cx,    %di
        addw    $1,     %di
        movw    %di,    -8(%bp)
        movw    %ax,    %di
        adcw    $0,     %di
        movw    %di,    -6(%bp)
        movw    %dx,    %di
        adcw    $0,     %di
        movw    %bx,    %ax
        adcw    $0,     %ax
        movw    %ax,    -2(%bp)
        movw    -8(%bp),        %ax
        movw    %ax,    (%si)
        movw    -6(%bp),        %ax
        movw    %ax,    2(%si)
        movw    %di,    4(%si)
        movw    -2(%bp),        %ax
        movw    %ax,    6(%si)
        movw    %si,    %ax
        movw    %bp,    %sp
        popw    %bp
        popw    %di
        popw    %si
        ret     $8
        .size   frobfrobfrob, .-frobfrobfrob
```
while with `-mregparmcall -O2` the output is better, both size-wise and speed-wise:
```asm
        .global frobfrobfrob
        .type   frobfrobfrob, @function
frobfrobfrob:
        pushw   %si
        pushw   %di
        pushw   %bp
        movw    %sp,    %bp
        movw    8(%bp), %dx
        movw    10(%bp),        %bx
        movw    12(%bp),        %cx
        movw    14(%bp),        %si
        addw    $1,     %dx
        adcw    $0,     %bx
        adcw    $0,     %cx
        adcw    $0,     %si
        movw    %ax,    %di
        movw    %dx,    (%di)
        movw    %bx,    2(%di)
        movw    %cx,    4(%di)
        movw    %si,    6(%di)
        popw    %bp
        popw    %di
        popw    %si
        ret     $8
        .size   frobfrobfrob, .-frobfrobfrob
```
(But perhaps this is an atypical case, and I am worrying a bit too much. ☺)

Thank you!

**Comment by tkchia** [comment]
I am thinking of further updating the `regparmcall` ABI to allow, say, the 32-bit offset argument to `lseek` to go into `%cx:%dx`, rather than onto the stack.

(The stack passing is (in a way) a leftover detail from my earlier attempt to imitate `__watcall`, which does not allow a 32-bit argument to straddle the `%dx:%ax` and `%cx:%bx` pairs.)

I will see if I can get this ABI change implemented and tested some time soon.

Thank you!

**Comment by bartoldeman** [comment]
It seems that that example with `long long` is independent of regparm, as it also happens to generate worse code for `-Os` without that switch. I looked if any specific `-f` flag caused it but could not find it, for what it's worth, `-O1` also generates good code.

So something included in `-Os` causes bad code, which is good to know.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

> So something included in `-Os` causes bad code, which is good to know.

Thanks!  This does seem useful to know.
