### ISSUE TITLE
ICE with embedded string in far struct

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#3]
Here's another issue, independent of the optimizer:
```
extern void farstr(char __far * s);

struct string1 {
  char str[1];
};

void call_farstr(struct string1 __far *p)
{
  farstr(p->str);
}
```

gives me 
```
trying to convert pointer or address in address space 0
with unexpected mode:
(mem/f/c:SI (reg/f:HI 15 virtual-incoming-args) [1 p+0 S4 A16])
test2.c: In function ‘call_farstr’:
test2.c:9:10: internal compiler error: in convert_memory_address_addr_space_1, at explow.c:298
   farstr(p->str);
          ^
0x8307e51 convert_memory_address_addr_space_1(machine_mode, rtx_def*, unsigned char, bool, bool)
        ../../gcc-ia16/gcc/explow.c:298
0x8307e79 convert_memory_address_addr_space(machine_mode, rtx_def*, unsigned char)
        ../../gcc-ia16/gcc/explow.c:400
0x831ccae expand_expr_addr_expr
        ../../gcc-ia16/gcc/expr.c:7810
0x831ccae expand_expr_real_1(tree_node*, rtx_def*, machine_mode, expand_modifier, rtx_def**, bool)
        ../../gcc-ia16/gcc/expr.c:10867
0x8326576 store_expr_with_bounds(tree_node*, rtx_def*, int, bool, bool, tree_node*)
        ../../gcc-ia16/gcc/expr.c:5409
0x8327ef9 expand_assignment(tree_node*, tree_node*, bool)
        ../../gcc-ia16/gcc/expr.c:5175
0x8253bbe expand_gimple_stmt_1
        ../../gcc-ia16/gcc/cfgexpand.c:3618
0x8253bbe expand_gimple_stmt
        ../../gcc-ia16/gcc/cfgexpand.c:3714
0x8255e1b expand_gimple_basic_block
        ../../gcc-ia16/gcc/cfgexpand.c:5720
0x825abd6 execute
        ../../gcc-ia16/gcc/cfgexpand.c:6335
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

**Comment by bartoldeman** [comment]
This can be worked around using `&p->str[0]`

**Comment by tkchia** [comment]
Hello @bartoldeman,

Sorry for this (relatively) long-running bug.  At the moment this seems to me to be an issue in GCC's machine-independent GENERIC tree code --- so it may well also apply to other GCC ports which support named address spaces (e.g. recent x86-32/-64).

Apparently `p->str` is computed by taking the address of an array of characters (considered as a block of bytes?) in `__far` space, and then casting the address to type "`__far` pointer to character" (`array_to_pointer_conversion (`...`)` in `gcc/c/c-typeck.c`), but at some point, the fact that the array is in `__far` space somehow gets lost, leading to weirdness.

Anyway, I will continue to see what I can do about this bug.  Thank you!

**Comment by bartoldeman** [comment]
Don't worry about the delay.. I am quite happy to see that finally after 17 years GCC can have a go at compiling the FreeDOS kernel. I'll keep submitting bug reports for small test cases but we are getting close in particular with optimizations disabled.
