### ISSUE TITLE
stack spilling using `-mregparmcall`

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#31]
I tried to get an example as small as possible (from fattab.obj in FreeDOS kernel which does save > 2K by using mregparmcall):

```
struct j {
  char j;
};
struct a {
  unsigned char flag;
  struct j __far *pj;
};
extern struct a __far *fnc(int i, int j);
void foo(struct j __far * pj)
{
  struct a __far *p = fnc(0, pj->j);
  if (p)
  {
    p->flag &= ~1;
    p->pj = pj;
  }
}
```
if you compile this with `-mregparmcall -Os -S` you'll notice a weird instruction:
`movb    %al,    -1(%bp)` but that location is never read back.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

Thanks for the report!  I think I will need a bit more time to properly fix this.

(It seems that GCC, for whatever reason, thinks an extra register or memory slot is needed to sign-extend `pj->j` --- using the `extendqihi2` insn pattern, which ultimately expands to `cbtw` --- and this only happens for `regparmcall` functions.)
