### ISSUE TITLE
Space-consuming 32-bit division/modulo routines in libgcc

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#32]
It seems that ia16-elf-gcc uses some generic 32-bit routines for __udivsi3, __umodsi3 and friends.
They weigh in heavily:
__udivsi3: 0x633 = 1587 bytes
__umodsi3: 0x58c = 1420 bytes
for 3K total.

There are some alternatives: if you want to stick with C it looks like libgcc/udivmodsi4.c and udivmod.c should generate smaller code. The FreeDOS kernel uses an asm implementation that takes  0x94 = 148 bytes total.
https://github.com/FDOS/kernel/blob/e6d427834fb5f414ecb984b87454d5df39f2f571/kernel/ludivmul.inc

**Comment by bartoldeman** [comment]
Seems that adding inline asm to include/longlong.h will go a long way, in fact just a copy of the i386 code with some adjustments.

**Comment by tkchia** [comment]
Hello @bartoldeman ,

I think I _might_ also be able to add assembly implementations of `__udivsi3` and `__umodsi3` routines to `libgcc` (in place of the C versions).  I will give it a try when I have time.

Thank you!

**Comment by zfigura** [comment]
On the other hand, here's yet another reason to support 32-bit size overrides :-)

**Comment by tkchia** [comment]
Hello @zfigura,

Well, you _can_ already write, say, `divl %ebx` under the assembler, if that is what you mean.  Of course, there are caveats.

Thank you!

**Comment by zfigura** [comment]
Sure, I mean generating them from gcc.

**Comment by tkchia** [comment]
Hello @zfigura ,

Well... yes, that should be a good thing to have, except that it would require blowing up the current back-end's whole system of register allocation (e.g. having an `%eax` around makes it much harder to get GCC to use `%dx:%ax` to return stuff, etc.).  So I am not sure that this is something I want to do. 😐

However, I think it might be feasible to compile an IA-32 routine using a standard _i386 compiler_, but with `-m16`, then link _that_ with IA-16 code compiled with `ia16-elf-gcc`.  The linking should work if both compilers output to ELF, but some "thunking" is probably needed on the IA-16 side to get the calling convention right.

Thank you!
