### ISSUE TITLE
Change `regparmcall` ABI for variadic functions to only push `...` arguments onto stack?

### ISSUE THREAD

**Issue by tkchia** [tkchia/gcc-ia16#35]
Currently the `regparmcall` calling convention falls back onto pushing all arguments onto the stack when the function being compiled is a variadic function.  I am considering changing it so that it will only push the variable arguments --- i.e. the `...` arguments --- onto the stack (in addition of course to any named arguments which do not fit into registers).

Since this may affect binary compatibility --- many standard C functions such as `printf`, `open`, etc. are variadic --- I would like to get some feedback first on whether this is a good idea.

Thank you!

**Comment by mfld-fr** [comment]
Not only the ... variables, but also the previous explicit variable, to allow stack walking, right ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

> Not only the ... variables, but also the previous explicit variable, to allow stack walking, right ?

Not necessarily --- it turns out that GCC's machine-independent middle-end allows me to choose whether the final named argument is or is not always passed on the stack (!).

So I guess that is another choice for me to make, which I would also like to get some feedback on.

(GCC's middle-end specially implements `va_start (`_ap_, _last_`)` so that it does not need an address for the _last_ argument in order to work.  And from what I know, some non-x86 calling conventions, such as ARM AAPCS, actually allow all named arguments to go into registers.)

Thank you!
