### ISSUE TITLE
[question] No use of DS & ES at all

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/gcc-ia16#39]
Hello @tkchia,

Sorry to come back again to something that has already been discussed many times (including about the "protected mode" in tkchia#21), but I really need for ELKS the compiler to NOT touch at all to the current DS et ES registers, except when dealing with far pointers.

This would allow me to implement a "segment checking" in the EMU86 tool, to break execution when moving back & forth from kernel to user space, and / or catching accesses to specific segments, to ease my current debugging. If the compiler still uses ES & DS for other things than far pointers, it makes that feature hard to design.

Is this behavior exactly what the option "-protected-mode" implies ? Or could it be possible to have this behavior when using the existing '-elks' option, to not impact the other GCC-IA16 users ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

Yes, either `-mprotected-mode` or `-melks` should do exactly what you need.  I have recently also tweaked the `-melks` option to also enable `-mprotected-mode` on default.

The output code should avoid using `%ds` or `%es` for things other than far pointer segments (and values wrapped in `__builtin_ia16_selector (.)`).

If you come across any cases where `gcc-ia16` violates this behaviour, this is a bug --- please let me know about it.

Thank you!

**Comment by mfld-fr** [comment]
Thank you very much, that is perfect. Let me add this option in the 'elks/gcc-ia16' branch. I also have to update our build script to pick up your latest version with the 'i186' / 'i286' aliases.
