### ISSUE TITLE
Too long comparison code with '-Os' ?

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/gcc-ia16#42]
I am getting mad while debugging the comparisons generated by `gcc-ia16` :smile: !

Latest thing I don't understand: from https://github.com/jbruchon/elks/blob/switch-to-gcc/libc/misc/strtol.c:
```
unsigned long int
strtoul(const char *nptr, char **endptr, int base)
{
  unsigned long int number;

  /* Sanity check the arguments */
  if (base==1 || base>36 || base<0)
    base=0;
```
Generated code:
```
1CB7:1F8C  56                 PUSH    SI
1CB7:1F8D  57                 PUSH    DI
1CB7:1F8E  55                 PUSH    BP
1CB7:1F8F  89 E5              MOV     BP,SP
1CB7:1F91  83 EC 06           SUB     SP,6h
1CB7:1F94  83 7E 0C 01        CMP     [BP+Ch],1h
1CB7:1F98  9F                 LAHF
1CB7:1F99  D0 E4              SHL     AH,01h
1CB7:1F9B  99                 CWD
1CB7:1F9C  F6 DA              NEG     DL
1CB7:1F9E  83 7E 0C 25        CMP     [BP+Ch],25h
1CB7:1FA2  18 C0              SBB     AL,AL
1CB7:1FA4  FE C0              INC     AL
1CB7:1FA6  08 C2              OR      DL,AL
1CB7:1FA8  80 FA 01           CMP     DL,01h
1CB7:1FAB  19 C0              SBB     AX,AX
1CB7:1FAD  21 46 0C           AND     [BP+Ch],AX
```
Built that way:
```
ia16-elf-gcc -mtune=i8086 -fno-inline -mcmodel=small -mno-segment-relocation-stuff -ffreestanding -melks -I/mnt/data/home/mfld/advantech/elks-ia16/include -I/mnt/data/home/mfld/advantech/elks-ia16/libc/include -I/mnt/data/home/mfld/advantech/elks-ia16/elks/include -D__LIBC__ -D__LIBC_VER__='"elks-0.0"' -D__HAS_NO_FLOATS__ -Wall -O1 -c -o strtol.o strtol.c
```

**Comment by tkchia** [comment]
Hello @mfld-fr ,

The code seems to be working as it should (it leaves 2...36 alone, and turns anything outside of 2...36 into 0).  Are there any particular inputs for which `strtol` or `strtoul` returns the wrong answers?

Thank you!

**Comment by mfld-fr** [comment]
Sorry, I was not clear in my problem statement. Working code is not my concern here. My concern is actually the code size. Here the statement `a = (a == 1  || a >= 37) ? 0 : a;` is 28 bytes long. With the option `-Os`, I would expect it smaller, even at the price of branching & reloading the 8086 pipeline, just by using `cmp`, `jz` and `jnc` instructions.

**Comment by tkchia** [comment]
Hello @mfld-fr ,

That is true.  It seems that the current back-end tends to prefer emitting branch-less code, even if the equivalent branching code may be better size-wise --- and I am not sure how to fix this yet.  (GCC has a `-fno-if-conversion` flag, though it does not help much in this case.)

I think I will leave this issue open until I figure out how to deal with it.

Incidentally, if I rewrite the `if` statement as
```
if (base<2 || base>36)
  base = 0;
```
then GCC (with `-Os`) actually knows what to do with it:
```
strtoul:
	pushw	%si
	pushw	%di
	pushw	%es
	pushw	%bp
	movw	%sp,	%bp
	subw	$10,	%sp
	movw	14(%bp),	%si
	leaw	-2(%si),	%ax
	cmpw	$35,	%ax
	sbbw	%ax,	%ax
	andw	%ax,	%si
	...
```
Thank you!

**Comment by tkchia** [comment]
Hello @mfld-fr ,

It turns out that the back-end was wrongly computing the costs of branches --- it was using 80186 cycle counts regardless of optimization settings --- and I failed to notice that earlier.

After fixing this issue, with the `-Os` option the `strtoul` routine now looks like this:

```
strtoul:
	pushw	%si
	pushw	%di
	pushw	%es
	pushw	%bp
	movw	%sp,	%bp
	subw	$10,	%sp
	movw	14(%bp),	%si
	cmpw	$1,	%si
	je	.L22
	cmpw	$36+1,	%si
	jc	.L2
.L22:
	xorw	%si,	%si
.L2:
	movw	__ctype_ptr__,	%ax
	...
```

Thank you!

**Comment by mfld-fr** [comment]
Looks fine, thank you @tkchia ! By the way, I wonder why GCC activates `if-conversion` by default in `-Os` ? I could understand for processors with conditional instructions, but for IA16 ?

**Comment by tkchia** [comment]
Hello @mfld-fr ,

> By the way, I wonder why GCC activates `if-conversion` by default in `-Os` ? I could understand for processors with conditional instructions, but for IA16 ?

I am not totally sure, but the main GCC documentation suggests that there are "some tricks doable by standard arithmetics" which can work even on machines without conditionally-executed instructions.

Thank you!

**Comment by mfld-fr** [comment]
Yeah, true, as we saw in the first example through the LAHF instruction. Thanks !
