### ISSUE TITLE
Linking assembly object files with ia16-elf

### ISSUE THREAD

**Issue by jh-1** [tkchia/gcc-ia16#43]
ia16-elf-gcc looks great and I know there is a related assembler, ia16-elf-as. But has anyone had any success linking ia16-elf with Nasm?

Nasm reports that it can output the following object formats. 

valid output formats for -f are (`*' denotes default):
  * bin       flat-form binary files (e.g. DOS .COM, .SYS)
    ith       Intel hex
    srec      Motorola S-records
    aout      Linux a.out object files
    aoutb     NetBSD/FreeBSD a.out object files
    coff      COFF (i386) object files (e.g. DJGPP for DOS)
    elf32     ELF32 (i386) object files (e.g. Linux)
    elf64     ELF64 (x86_64) object files (e.g. Linux)
    elfx32    ELFX32 (x86_64) object files (e.g. Linux)
    as86      Linux as86 (bin86 version 0.3) object files
    obj       MS-DOS 16-bit/32-bit OMF object files
    win32     Microsoft Win32 (i386) object files
    win64     Microsoft Win64 (x86-64) object files
    rdf       Relocatable Dynamic Object File Format v2.0
    ieee      IEEE-695 (LADsoft variant) object file format
    macho32   NeXTstep/OpenStep/Rhapsody/Darwin/MacOS X (i386) object files
    macho64   NeXTstep/OpenStep/Rhapsody/Darwin/MacOS X (x86_64) object files
    dbg       Trace of all info passed to output stage
    elf       ELF (short name for ELF32)
    macho     MACHO (short name for MACHO32)
    win       WIN (short name for WIN32)

**Comment by bartoldeman** [comment]
Sure, it's done in the FreeDOS kernel and freecom ports to ia16-elf-gcc. You need to use `-f elf` and `bits 16` in the source file. E.g. for freecom we have this include blurb for portability between OMF and ELF:
```
%ifidn __OUTPUT_FORMAT__, obj
group   DGROUP          _DATA _BSS
segment _TEXT           class=CODE
segment _DATA           class=DATA align=2
segment _BSS            class=BSS align=2
%else
bits 16
%define _TEXT .text
%define _DATA .data
%define _BSS .bss
%endif
```

**Comment by jh-1** [comment]
The ia16-elf commands are at least trying to compile and link but coming up with various errors. Did you have to use any particular command-line switches?

**Comment by tkchia** [comment]
Hello @jh-1,

Can you let us know what error messages you are getting precisely, and what commands and inputs you provided to `ia16-elf-gcc` (and friends) that were giving these errors?

Thank you!

**Comment by jh-1** [comment]
Yes, will do. To be clear, I am not saying the utilities are at fault, just trying to find out how to combine them with Nasm. 

The current bin86 set of assemble, compile and link commands which work (or appear to work; it's possible that there are source problems which the bin86 utils don't notice) are of the form

nasm -f as86 -o <dest> <src>
bcc -ansi -c -o <dest> <src>
ld86 -d -i -o <dest> <srcs> -M > <symfile>

The new build commands are of the form 

nasm -f elf -D_TEXT=.text -D_DATA=.data -D_BSS=.bss -o <dest> <src>
ia16-elf-gcc -fleading-underscore  -c -o <dest> <src>
ia16-elf-ld -o <dest> <srcs> -M > <symfile>

Neither the assembles nor the compiles report errors but the linker reports two kinds:

start_at16.nasm:(.text+0x45): relocation truncated to fit: R_386_16 against symbol `cs_boot_dl' defined in .text section in ox16/code_final.o

and

ia16-elf-ld: ox16/sformat.o: in function `_.L7':
(.text+0x85): undefined reference to `___udivsi3'

That's why I wondered if other command-line switches were needed to link with 16-bit Nasm object files.

**Comment by jh-1** [comment]
Yes, will do. To be clear, I am not saying the utilities are at fault, just trying to find out how to combine them with Nasm.

My current bin86 set of assemble, compile and link commands which work (or appear to work; it's possible that there are source problems which the bin86 utils don't notice) are of the form

nasm -f as86 -o dest source
cc -m16 -Wall -Wextra -Werror -c -o dest source
bcc -ansi -c -o dest source
ld86 -d -i -o dest sources -M > symfile

The output from the cc command is not kept and does not form part of the build. The command is there only because its diagnostics are stronger than bcc's; it's being used like the old lint checker.

The new build commands are of the form

nasm -f elf -D_TEXT=.text -D_DATA=.data -D_BSS=.bss -o dest source
ia16-elf-gcc -fleading-underscore -c -o dest source
ia16-elf-ld -o dest sources -M > symfile

Neither the assembles nor the compiles emit error messages but the linker reports what seem to be two kinds. Here are complete examples:

start_at16.nasm:(.text+0x45): relocation truncated to fit: R_386_16 against symbol `cs_boot_dl' defined in .text section in ox16/code_final.o

and

ia16-elf-ld: ox16/sformat.o: in function _.L7': (.text+0x85): undefined reference to ___udivsi3'

Hence my query about whether other command-line switches were needed to link with 16-bit Nasm object files.

**Comment by tkchia** [comment]
Hello @jh-1,

> `start_at16.nasm:(.text+0x45): relocation truncated to fit: R_386_16 against symbol `cs_boot_dl' defined in .text section in ox16/code_final.o`

Ah, yes --- we forgot to mention that, if you are linking directly with `ia16-elf-ld` (not the `ia16-elf-gcc` front-end), you will most probably need to specify a [_linker script_](https://sourceware.org/binutils/docs/ld/Scripts.html) to use, or else `ia16-elf-ld` will try to do something bogus.  As a quick start, you can try to write a file `binary.ld` that says
```
OUTPUT_FORMAT(binary)
ENTRY(_start)
SECTIONS
  {
    . = 0;
    .text : {
		*(.text) *(.text.*)
	}
    .data : {
		*(.rodata) *(.rodata.*)
		*(.data) *(.data.*)
		*(.gcc_except_table)
	}
    .bss (NOLOAD) : {
                *(.bss) *(.bss.*)
                *(COMMON)
	}
    /DISCARD/ : { *(.*) }
  }
```
then add the option `-Tbinary.ld` to the `ia16-elf-ld` command line.

> `ia16-elf-ld: ox16/sformat.o: in function _.L7': (.text+0x85): undefined reference to ___udivsi3'`

This error is because the C compiler sometimes outputs calls to compiler helper routines (`__udivsi3` is for dividing an unsigned 32-bit integer by another 32-bit integer).

To fix this, you can link in the `libgcc` library using the `-lgcc` option.  (Alternatively, you can implement `__udivsi3` directly in your project.)

Therefore:
```
ia16-elf-ld -Tbinary.ld -o dest sources -lgcc -M > symfile
```

Thank you!

**Comment by tkchia** [comment]
Hello @jh-1,

In case you would like to know more: if you invoke the linker through the `ia16-elf-gcc` front-end, the front-end will by default select a linker script suitable for building "normal" MS-DOS `.exe` files (if you say `-mcmodel=small`) or MS-DOS `.com` files.

You can view the linker script used in a particular link step by adding a `-Wl,--verbose` option, like so:
```
ia16-elf-gcc -mcmodel=small hello.c -o hello.exe -Wl,--verbose
```

Currently both FreeCOM and the FreeDOS kernel use custom linker scripts, since they need to lay out their memory areas in very specific ways.

Thank you!

**Comment by jh-1** [comment]
Much appreciated. That's very helpful. I'll have to explore the options to see what works best. 

As for -lgcc this is for bare-metal code so (as long as I can find what calling conventions are needed) I may well end up writing the helper routines, as you suggest. 

Just to let you know what's happening I have tried the linker script and it gets me past the "relocation truncated" issue but I now get

ia16-elf-ld -Tbinary.ld -o ex16/ost16.com ox16/start_at16.o ox16/debuga.o ox16/intr_rx.o ox16/intr_recognition.o ox16/lista.o ox16/mspace16.o ox16/osinit.o ox16/panic_x16.o ox16/sysvars_x16.o ox16/vgao.o ox16/x86_16.o ox16/cmos_io.o ox16/cmosrtcb.o ox16/dtim_16.o ox16/port_8.o ox16/bootvars.o ox16/dnode.o ox16/idle_task.o ox16/intrh.o ox16/kbc.o ox16/kernel_call_handler.o ox16/picmgr.o ox16/pitmgr.o ox16/scheda.o ox16/sformat.o ox16/sysvars.o ox16/tasksb.o ox16/code_final.o -lgcc -M > ex16/ost16.syms
ia16-elf-ld: cannot find -lgcc

I have installed from packages, and updated to the latest, currently

$ apt list --installed | grep ia16
binutils-ia16-elf/bionic,now 2.31.51-20190407.07-ppa190412165~bionic amd64 [installed,automatic]
gcc-ia16-elf/bionic,now 6.3.0-20190409.16-ppa190412172~bionic amd64 [installed]
libnewlib-ia16-elf/bionic,now 2.4.0-20190407-stage1gcc6.3.0-20190409.16-binutils2.31.51-20190407.07-ppa190412172~bionic amd64 [installed
,automatic]
$

but I guess the -lgcc error means I need to do something to tell ld where to look to find the library. If it's libgcc.a there seem to be various copies. 

$ find / -name *libgcc* 2>/dev/null | grep ia16
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/frame-pointer/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/libgcc.a
$

So I'm not sure what to do next but will come back to this.

**Comment by jh-1** [comment]
Much appreciated. That's very helpful. I'll have to explore the options to see what works best.

As for -lgcc this is for bare-metal code so (as long as I can find what calling conventions are needed) I may well end up writing the helper routines, as you suggest.

Just to let you know what's happening I have tried the linker script and it gets me past the "relocation truncated" issue but I now get

ia16-elf-ld -Tbinary.ld -o ex16/ost16.com ox16/start_at16.o ox16/debuga.o ox16/intr_rx.o ox16/intr_recognition.o ox16/lista.o ox16/mspace16.o ox16/osinit.o ox16/panic_x16.o ox16/sysvars_x16.o ox16/vgao.o ox16/x86_16.o ox16/cmos_io.o ox16/cmosrtcb.o ox16/dtim_16.o ox16/port_8.o ox16/bootvars.o ox16/dnode.o ox16/idle_task.o ox16/intrh.o ox16/kbc.o ox16/kernel_call_handler.o ox16/picmgr.o ox16/pitmgr.o ox16/scheda.o ox16/sformat.o ox16/sysvars.o ox16/tasksb.o ox16/code_final.o -lgcc -M > ex16/ost16.syms
ia16-elf-ld: cannot find -lgcc

I have installed from packages, and updated to the latest, currently

$ apt list --installed | grep ia16
binutils-ia16-elf/bionic,now 2.31.51-20190407.07-ppa190412165\~bionic amd64 [installed,automatic]
gcc-ia16-elf/bionic,now 6.3.0-20190409.16-ppa190412172\~bionic amd64 [installed]
libnewlib-ia16-elf/bionic,now 2.4.0-20190407-stage1gcc6.3.0-20190409.16-binutils2.31.51-20190407.07-ppa190412172~bionic amd64 [installed,automatic]
$

but I guess the -lgcc error means I need to do something to tell ld where to look to find the library. If it's libgcc.a there are various copies.

$ find / -name libgcc 2>/dev/null | grep ia16
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/regparmcall/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/frame-pointer/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/any_186/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/any_186/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/size/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/rtd/libgcc.a
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/libgcc.a
$

At this point I'm not sure what's best to do next ... but will come back to it.

**Comment by mfld-fr** [comment]
@jh-1 If you write the `udivsi3` routine, I would be very interested in your version, because we did it in our project, and I am wondering if someone could write a better one: https://github.com/jbruchon/elks/tree/master/libc/gcc

**Comment by ecm-pushbx** [comment]
Here's your main function for that:  https://github.com/jbruchon/elks/blob/f8d6df8d0babe6620213caa59aa990335d72f453/libc/gcc/ldivmod.s

Here's the one from my debugger. Note that this assumes unsigned arithmetic. https://bitbucket.org/ecm/ldebug/src/49eb5bad57a9f3912c7e20ecf48300154cfa5202/source/expr.asm#lines-1039

```
of_divide:			; bx:dx := var / bx:dx
	 push bx
	or bx, dx		; divisor zero ?
	 pop bx
	jz error		; divisor zero !
	_386_jmps .32		; 386, use 32-bit code -->
	test bx, bx		; need only 16-bit divisor ?
	jnz .difficultdiv16	; nope -->
	mov cx, dx
	xor dx, dx
	mov ax, word [hhvar+2]	; dx:ax = high word of previous number
	div cx
	mov bx, ax
	mov ax, word [hhvar]	; ax = low word of previous number, dx = remainder
	div cx
	mov dx, ax		; bx:dx = result
	retn

.difficultdiv16:		; code adapted from Art of Assembly chapter 9
				; refer to http://www.plantation-productions.com/Webster/www.artofasm.com/DOS/ch09/CH09-4.html#HEADING4-99
	mov cx, 32
	push bp
	push si
	push di
	mov ax, word [hhvar]
	mov bp, word [hhvar+2]	; bp:ax = previous number
	xor di, di
	xor si, si		; clear variable si:di
	xchg ax, dx
	xchg bp, bx		; bx:dx = previous number, bp:ax = divisor
.bitloop:
	shl dx, 1
	rcl bx, 1
	rcl di, 1
	rcl si, 1		; si:di:bx:dx << 1
	cmp si, bp		; does the divisor fit into si:di here ?
	ja .goesinto
	jb .trynext
	cmp di, ax
	jb .trynext		; no -->
.goesinto:
	sub di, ax
	sbb si, bp		; subtract divisor
	inc dx			; set a bit of the result (bit was zero before, never carries)
.trynext:
	loop .bitloop		; loop for 32 bits
	pop di
	pop si
	pop bp
	retn
```

**Comment by mfld-fr** [comment]
@ecm-pushbx Looks far shorter, I like it and will try your version. Thank you !

**Comment by tkchia** [comment]
Hello @jh-1,

> `ia16-elf-ld: cannot find -lgcc`

Oops --- _mea culpa_.  I forgot (again) that the path to `libgcc.a` is known to the GCC driver and not to `ia16-elf-ld`.  GCC has an option to output the correct path: if you say

> `ia16-elf-gcc` _compiler-options_ `-print-libgcc-file-name`

then GCC will write to stdout the path to `libgcc.a` for the given set of compiler options.  You can thus insert a call to `ia16-elf-gcc` ... `-print-libgcc-file-name` into the linker command line to link in the correct library.

Thank you!

**Comment by tkchia** [comment]
Hello @jh-1,

In the near future I hope to make it easier to make it easier to use the `ia16-elf-gcc` driver program (together with `-nostdlib`) to build 8086 binaries other than MS-DOS `.com` or `.exe` programs.

Thank you!

**Comment by jh-1** [comment]
Hello @tkchia,

No problem! I know how difficult it is to work remotely and by a system akin to email, and I appreciate the guidance. 

But I seem to have hit another snag. I tried ia16-elf-gcc ... -print-libgcc-file-name with various options and all pointed to the same libgcc.a so I set up my makefile with

ia16_libdir := $(dir $(shell ia16-elf-gcc -print-libgcc-file-name))
LDX16 := ia16-elf-ld -Tbinary.ld -L $(ia16_libdir)

That executed the following command (with the object files where I've put the ellipsis) 

ia16-elf-ld -Tbinary.ld -L /usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/ -o ex16/ost16.com ... -lgcc -M > ex16/ost16.syms

but still the link could not find `___udivsi3', `___modsi3', and `___divsi3'. 

If it's relevant, an objdump -t on the libgcc.a came up with an attribute of .hidden which is new to me. 

00000000 g     F .text  00000000 .hidden __udivsi3

In the long term I will probably need the extra control that running the linker separately can give but at least for now I thought I should try linking with the compiler

ia16-elf-gcc -o ex16/ost16.com ...

I may be running it wrongly. At any rate, I thought I should mention it as that also declares undefined references to `___udivsi3', `___modsi3' and `___divsi3'. 

Unless my installation is incorrect in some way it's possible I am approaching this wrong and need to start with something small but which works and go from there.

**Comment by tkchia** [comment]
Hello @jh-1,

> I may be running it wrongly. At any rate, I thought I should mention it as that also declares undefined references to ___udivsi3`, `___modsi3` and `___divsi3'.

I cannot reproduce this problem on my end --- I have no problem linking programs that use `__udivsi3`:
```
$ cat foo.c
unsigned long x, y, z;

void _start (void)
{
  z = x / y;
}
$ ia16-elf-gcc -nostdlib -Os foo.c -lgcc -Wl,-M
...
LOAD /tmp/ccXmTCaw.o
LOAD /home/user/.local/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/size/libgcc.a
OUTPUT(a.out binary)
```

What do you get when you add the switch `--verbose` (if linking with `ia16-elf-ld`) or `-Wl,--verbose` (if linking with `ia16-elf-gcc`)?  The output should provide some information on how `ia16-elf-ld` is searching for libraries and resolving references.

> If it's relevant, an objdump -t on the libgcc.a came up with an attribute of .hidden which is new to me.

> `00000000 g F .text 00000000 .hidden __udivsi3`

Thanks --- I will see if this is something that needs fixing; though I see that my setup also has symbols marked `.hidden`, and the linker still sees them.  (It [seems](https://stackoverflow.com/questions/11329734/what-does-hidden-mean-in-the-output-of-output-objdump-t) that the `.hidden` attribute is mainly relevant for systems that use shared objects.)

Thank you!

**Comment by jh-1** [comment]
Hello @tkchia,

Sorry for the delay in replying but I hadn't worked out what was wrong. I think I may have just found the remaining problem. And now I have it's fairly obvious. It was due to compiling with 

    ia16-elf-gcc -fleading-underscore -c -o dest source

The leading-underscore switch was there because to work with my prior compiler (bcc) my Nasm sources had had to include underscore prefixes. If I am going to commit to ia16-elf I will just remove the underscores so it can easily be dealt with.

One question: Should the manpages work for ia16-elf-gcc and the others? If so I will submit a separate report.

Thanks for your help with getting this problem fixed.

**Comment by tkchia** [comment]
Hello @jh-1,

> I think I may have just found the remaining problem. And now I have it's fairly obvious.

Glad to hear that!

> One question: Should the manpages work for ia16-elf-gcc and the others? If so I will submit a separate report.

Yes, they probably should --- I will look into this.

Meanwhile, you can consult the `info` pages on the options and features that have been added specifically for the IA-16 port.  If you are using my Ubuntu PPA (https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16/) then you can try this command:

```
info /usr/ia16-elf/info/gcc.info
```

Thank you!

**Comment by jh-1** [comment]
I see you've added a note about man pages so I won't open another report unless you want me to. For the record, what I see at the moment is

$ man ia16-elf-gcc
timestamp
 Manual page ia16-elf-gcc(1) line 1/2 (END) (press h for help or q to quit)

While I prefer man pages I can get to and use the info files you mentioned earlier. 

Thanks again. Will close this case now.

**Comment by tkchia** [comment]
Hello @jh-1,

Thank you for the information.  I have uploaded a new set of Ubuntu packages for the toolchain, and the man pages should work properly now.

Thank you!
