### ISSUE TITLE
Ubuntu packages for Eoan?

### ISSUE THREAD

**Issue by andrewbird** [tkchia/gcc-ia16#47]
Hi, sorry for troubling you, but I've just upgraded my Lubuntu machine. I just tried to install your ia16-elf-gcc and find you only have packages for the LTS versions, is there any chance you can release some for Eoan, else I'll need to reinstall?

Hope you can help, thanks, Andrew!

**Comment by tkchia** [comment]
Hello @andrewbird,

I will see what I can do.  Thanks!

**Comment by tkchia** [comment]
Hello @andrewbird,

It seems Launchpad has some trouble building `gcc-ia16` (based on GCC 6.3.0) together with the newer `libisl` that comes with Eoan.  I will need to look into how to tackle this problem.  Thank you!

**Comment by andrewbird** [comment]
@thchia. There are quite a few things in general I'm not happy about in my Lubuntu 18.04(32bit) -> 19.10(64bit) upgrade, so I think I'll revert to Bionic(64bit). Thanks very much for looking at this for me, but don't waste any more time on it on my account.

Thanks again!
