### ISSUE TITLE
Possible optimization opportunities

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#48]
Here is a little example:
```
extern int foo(int);
int bar(int a, int b)
{       int baz = foo(b);
        return a || baz < b;
}
```
if I compile with `-Os -mregparmcall` I get 43 bytes, but with Open Watcom 25 bytes (using `-os -s`)
A pattern in there that could be avoided is the last line in
```
   0:   56                      push   si
   1:   55                      push   bp
   2:   89 e5                   mov    bp,sp
   4:   1e                      push   ds
   5:   96                      xchg   si,ax
   6:   89 d0                   mov    ax,dx
   8:   89 56 fe                mov    WORD PTR [bp-0x2],dx
```
you see here that `ds` is pushed (dummy value) but later `dx` is put in the same place. So `dx` could be pushed directly instead thereby eliminating the need for the frame pointer.

If you compile with `-fno-caller-saves` it uses `si` instead of the stack entry, and `di` instead of `si` so the code size goes down to 31 bytes (and `bp` is no longer used). However the above pattern occurs with `-fno-caller-saves` too in more complex code.

**Comment by tkchia** [comment]
Hello @bartoldeman,

Thanks for the report.  My understanding is that `-fcaller-saves` (enabled with `-Os`) should, by right, not result in worse code than `-fno-caller-saves`.  I will need to find out what is going on here.

Thank you!

**Comment by tkchia** [comment]
Hello @bartoldeman,

I have added an optimization subpass to do something along the lines of what you proposed.

(As always, of course, I will need to do further tests on it to make sure it does not break anything.)

Thank you!

**Comment by tkchia** [comment]
Hello @bartoldeman,

Further down the compiled code, there is this bit which makes it a bit hard to get rid of the frame pointer `%bp`:
```
	movw	-2(%bp),	%dx
	xorb	%cl,	%cl
	cmpw	%ax,	%dx
	jle	.L2
	movb	$1,	%cl
.L2:
	...
	movw	%bp,	%sp
	popw	%bp
	popw	%si
	ret
```
I think it will be nice if GCC can somehow change the move into `%dx` into a `popw %dx`, but my optimization subpass does not do that yet.

Thank you!
