### ISSUE TITLE
Unreal mode in GCC-IA16?

### ISSUE THREAD

**Issue by tkchia** [tkchia/gcc-ia16#49]
From https://github.com/elks-org/elks/issues/320#issuecomment-584765550 :

> [@georgp24:]
> @tkchia
> A question on a different topic : if I set ELKS into unreal mode, could I address memory above 1 MB with GCC-IA16? E.g. with embedded ASM commands?

**Comment by tkchia** [comment]
Hello @georgp24,

Well, the `gcc-ia16` back-end does not really know about 32-bit registers or unreal mode --- whether for ELKS, MS-DOS, or other IA-16 OSes.

You can probably write something like
```
__asm ("...; movl (%%ebx), %%eax; ..." : ... : ...)
```
and the GNU assembler will know how to assemble it, but then you will have the problem of moving the correct values into `%ebx` and out of `%eax` (either through a pair of 16-bit registers, or through memory).

Alternatively, you can bypass the compiler and write your unreal mode routines completely in assembly language (but with `.code16`).  The GNU assembler in `binutils-ia16` is mostly the same as the standard GNU assembler for x86-32.

Thank you!

**Comment by georgp24** [comment]
Hi @tkchia,
thank you for your answer. I look for a way to test if the cpu has been successfully set into unreal mode. I found this snippet which pokes characters into video memory in real and unreal mode:

                mov ax,0xB800           ; real mode
                mov es,ax
                mov byte [es:0],'A'
                        ...
                mov byte [es:2],'B'

                xor ax,ax               ; unreal mode
                mov es,ax
                mov byte [es: dword 0xB8000],'A'
                        ...
                mov byte [es: dword 0xB8002],'B'

My main question is: How would you write the " mov byte [es: dword 0xB8000],'A' " command in __asm (..) syntax?

**Comment by tkchia** [comment]
```
.code16
...
addr32 movb $'A', %es:0xb8000
```

Within an extended `asm` statement in C, you probably need to double the `%`, e.g.

`asm ... ("...; addr32 movb $'A', %%es:0xb8000; ...");`

Thank you!

**Comment by georgp24** [comment]
Thank you tkchia!

**Comment by tkchia** [comment]
Hello @georgp24,

No problem. :)  Do let me know if you have any more questions.  Thank you!
