### ISSUE TITLE
Link as86 object file with gcc-ia16?

### ISSUE THREAD

**Issue by georgp24** [tkchia/gcc-ia16#51]
I am used to write assembler code in Intel syntax. NASM supports the "-f as86" output format. I could link this output format with bcc and run the program with ELKS. This is documented in the "elks/Documentation/html/user/writing_apps_in_assembler.html" file. Is there a way to do that with gcc-ia16 too? Here is the section from the NASM manual:

> 7.12 as86: Minix/Linux as86 Object Files
> 
> The Minix/Linux 16-bit assembler as86 has its own non-standard object file format. Although its 
> companion linker ld86 produces something close to ordinary a.out binaries as output, the object 
> file format used to communicate between as86 and ld86 is not itself a.out.
> 
> NASM supports this format, just in case it is useful, as as86. as86 provides a default output file-
> name extension of .o.
> 
> as86 is a very simple object format (from the NASM user's point of view). It supports no special 
> directives, no use of SEG or WRT, and no extensions to any standard directives. It supports only 
> the three standard section names .text, .data and .bss. The only special symbol supported is ..start.

**Comment by tkchia** [comment]
Hello @georgp24,

Thanks for your feedback!  I will see what I can do to support `as86`'s output format (once I get around to it).

**Comment by tkchia** [comment]
Hello @georgp24,

Incidentally, you can also use the `-f elf` option to `nasm` --- and, of course, use `bits 16` in the source file.  This will output ELF/i386 object files which `gcc-ia16` already supports.

Thank you!

**Comment by georgp24** [comment]
Thank you tkchia, I tried it and it worked.
`nasm -f elf -o hello.o hello.asm`
`ia16-elf-gcc -melks-libc -mcmodel=small -nostdlib hello.o -o hello`
This way you can use assembler code in Intel syntax for ELKS.
You also need to use `global _start`
