### ISSUE TITLE
snprintf problem

### ISSUE THREAD

**Issue by georgp24** [tkchia/gcc-ia16#53]
Hi @tkcia, does gcc-ia16 support snprintf()? This example will not compile:

compile with: `ia16-elf-gcc -o snprintf snprintf.c -melks-libc -mcmodel=small
`

```/* snprintf example */
#include <stdio.h>

int main ()
{
  char buffer [100];
  int cx;

  cx = snprintf ( buffer, 100, "The half of %d is %d", 60, 60/2 );

  if (cx>=0 && cx<100)      // check returned value

    snprintf ( buffer+cx, 100-cx, ", and the half of that is %d.", 60/2/2 );

  puts (buffer);

  return 0;
}

**Comment by tkchia** [comment]
Hello @georgp24,

This depends not on GCC _per se_, but on the toolchain's C library.  It seems that [ELKS](https://github.com/jbruchon/elks)'s C library does not implement `snprintf` yet.

(`snprintf` however works if you compile for MS-DOS.)

**Comment by tkchia** [comment]
Hello @georgp24,

I am "moving" this issue report over to the ELKS project.  Thank you!
