### ISSUE TITLE
Option -masm=intel seems to not be supported?

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#59]
I wanted to explore the output of gcc somewhat. I'd prefer for it to output Intel style assembly source. It seems that the option `-masm=intel` should do the trick, referenced eg https://stackoverflow.com/questions/199966/how-do-you-use-gcc-to-generate-assembly-code-in-intel-syntax

Am I putting it into the wrong place, or is it not supported by gcc-ia16? If so, please consider this a feature request.

```
$ ia16-elf-gcc --version
ia16-elf-gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ia16-elf-gcc test4.c -Os -S
$ ia16-elf-gcc test4.c -Os -S -masm=intel
ia16-elf-gcc: error: unrecognized command line option ‘-masm=intel’
$
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

> I wanted to explore the output of gcc somewhat. I'd prefer for it to output Intel style assembly source.

This is unfortunately not yet supported by `gcc-ia16` --- only the `i386` back-end really understands and supports this option.

Adding support is possible, but will involve a fair bit of work.  The various instruction patterns in the compiler's `ia16` back-end were written manually in AT&amp;T syntax.  So they will need to be manually updated to output Intel syntax.

As a (sort of poor man's) substitute, if you want to view the output of `gcc-ia16` in Intel syntax, you can try running `ia16-elf-objdump -D -Mi8086,intel` ... on the object (`.o`) files.

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

As you know I have added an implementation of `-masm=intel` --- I still consider it experimental, though it should be usable.  Let me know if you encounter any issues with it.  Thanks!

**Comment by ecm-pushbx** [comment]
Question: Which steps should I take in my build-ia16 copy to update to the latest newlib and gcc?

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

I just added an `update.sh` script to `build-ia16` which will try to pull updates.  So you can do this in the `build-ia16` tree:
```
git pull
./update.sh
```

Thank you!

**Comment by ecm-pushbx** [comment]
Thanks! Should I call build.sh afterwards? If so, which components need to be rebuilt?

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

You can just call `build.sh` to rebuild the bootstrap GCC, Newlib, and the final GCC:
```
./build.sh gcc1 newlib gcc2
```

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

I forgot to mention that I made a small fix to `binutils-ia16` to get it to compile under GCC 10 and above.  You can rebuild it too, i.e.
```
./build.sh binutils gcc1 newlib gcc2
```
but it is not essential.

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

I just fixed a(nother) bug in Newlib --- the BSS area was not initialized properly in some cases, when targeting the 80186+.  You might want to pull the updated Newlib and rebuild it.  Sorry for the trouble.  Thank you!
```
./update.sh
./build.sh newlib
```

**Comment by ecm-pushbx** [comment]
The Intel dialect option seems to work, thank you! For example, I can build [my tests](https://hg.ulukai.org/ecm/testia16) like this now:

```
$ ia16-elf-gcc test6.c -Os -S -masm=intel -mcmodel=medium
$ ia16-elf-gcc test6.s -Os -masm=intel -mcmodel=medium -o test6.exe
$ dosemu -dumb -quiet -K "$PWD" -E test6.exe
About to Execute : test6.exe
Hello world! a=00BC614Eh a=12345678 b=EAh b=234 c=FFEAh c=-22
d=0BC614E0h d=197530848 e=BC614E00h e=3160493568
$ 
```

There's a bit that I'm wondering about:

```
        push    di
        push    WORD PTR [-2+bp]
        push    di
        push    WORD PTR [-2+bp]
```

While correct, this seems unusual. Can you make it output "`[bp - 2]`" instead?

**Comment by ecm-pushbx** [comment]
Also, "`WORD PTR`" doesn't have to be allcaps I think.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

OK, I have made the changes you requested.  Thank you!

**Comment by ecm-pushbx** [comment]
Excellent, thanks a lot!
