### ISSUE TITLE
Missed optimisation: Do not modify sp before mov sp, bp

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#62]
Example: When building [my examples](https://hg.ulukai.org/ecm/testia16) test number 6 has the following section at the end of the main function:

```
$ ia16-elf-gcc test6.c -Os -S -masm=intel -mcmodel=medium
$ tail test6.s
        add     sp,     38
        xor     ax,     ax
        mov     sp,     bp
        pop     bp
        pop     es
        pop     di
        pop     si
        retf
        .size   main, .-main
        .ident  "GCC: (GNU) 6.3.0"
$
```

The `add sp, imm` is not needed before an only-write of `sp` in the function epilogue.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Thanks for your report.  The GCC middle-end does have a mechanism (`EXIT_IGNORE_STACK`) for removing such stack adjustments, but it seems to have some limitations.

I have added some peephole optimization rules to handle at least the case you mentioned.  The new code is in a separate Git branch; I will need to run further tests to make sure it works properly.

Thank you!

**Comment by tkchia** [comment]
@ecm-pushbx : the optimization should be there now.  Thank you!

**Comment by ecm-pushbx** [comment]
Great! When can we expect this to be stable enough to add to the main branch?

**Comment by tkchia** [comment]
@ecm-pushbx : I have already added the optimization to my main branch.  Thank you!

**Comment by ecm-pushbx** [comment]
I am asking because it does not appear in https://github.com/tkchia/gcc-ia16/commits/gcc-6_3_0-ia16-tkchia which is the default branch which github links to from the project's homepage.

**Comment by tkchia** [comment]
@ecm-pushbx : whoops, it seems I forgot to properly push to the default branch.  It should be there now.  Sorry and thank you!
