### ISSUE TITLE
ELKS kernel and far code segments

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#63]
Hello @tkchia,

I've been thinking further about far code segments, pursuant to our discussion https://github.com/tkchia/build-ia16/issues/14 back in April.

Now, instead of directly pursuing ELKS applications or the kernel being compiled fully medium model, I have been wondering about the capabilities of gcc-ia16 and the linker with regards to building the ELKS kernel with a single near code segment, used for most routines, and one or two far code segments, used for a kind-of "linked-in" kernel module approach. We've currently got about another 8k available in the kernel CS segment, and the idea would be to easily move a class of kernel code into a separate segment, to make more space in the near segment.

The first thoughts on the class of code I'm considering is the MINIX and FAT filesystem code, below the VFS layer. This code is already accessed only through function pointers, but there are of course "callbacks" to consider. The idea would be to take a directory of filesystem code, say elks/fs/msdos for the FAT fs, and specify a compiler option to compile all defined routines into far code in a single new segment. The "callback" routines, those which are not defined in fs/msdos, would each be separately specified as _far procedures in their headers and declarations, and the linker would link everything when the system is created. Another class of routines could be the kernel initialization code, although that is not contained in a single directory.

All data would remain near (kernel data segment).

For instance, here is the list of undefined functions for the FAT filesystem:
```
ELKS FAT Filesystem kernel callbacks

Code
 U lock_super
 U unlock_super

 U clear_inode
 U iput
 U __iget

 U bread
 U getblk
 U map_buffer
 U unmap_brelse

 U _wake_up
 U sleep_on

 U printk

 U memcpy
 U memcpy_fromfs
 U memcpy_tofs
 U memset
 U strcmp
 U strlen
 U strncmp
 U __divsi3
 U __modsi3
 U __udivsi3

 Function arrays (data)
 U blkdev_inode_operations
 U chrdev_inode_operations
```
From an initial look of it, there aren't many routines (other than all the FAT functions themselves) that would be affected, thus minimizing the speed cost for the kernel as a whole.

My questions are:
- Can a single, separate code segment be specified for all the routines in fs/msdos/?
- Can the callbacks be specified individually as _far and have the compiler/linker work for this multi-segment model?
- Would relocation be required in setup.S (or a called C routine) to relocate the far code segment relocations? How hard would this be to write, and where is that table kept?
- Since the block dev and char dev function arrays (blkdev_inode_operations) would also need to be far pointers, would just those entry points need to be far, or would everything they call need to be far as well?  I suppose the same question for any far callback function calling a near function applies.

It seems compiling both the FAT and MINIX filesystem drivers as far would help reduce the main near code segment quite a bit, without requiring the entire kernel to go medium model.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

Thanks for your comments.  I just recalled that I forgot to update `elksemu` to support the medium memory model.  I should really get around to doing that...

>   * Can a single, separate code segment be specified for all the routines in fs/msdos/?

In a way, yes.  In addition to specifying `__far` and the `far_section` attribute, you can force GCC to emit the code into a specified section, using GCC's (platform-independent!) `section` attribute.  So e.g.
```
static __far __attribute__ ((far_section, section (".fartext"))) minix_readdir (...)
{
    ...
}
```
(Of course all this verbiage should probably be wrapped up in a macro...)

For linking, the small-model linker script will need to be updated to place any `.fartext` in the input `.o` files in a `.fartext` segment in the output a.out file.  I will see if I can make this change.

>   * Can the callbacks be specified individually as _far and have the compiler/linker work for this multi-segment model?

Yes.  As explained in the `gcc-ia16` info file though, the syntax for declaring far function pointers is somewhat different from the "classical" syntax.  You can say e.g.
```
int __far (*readdir) ();
```
i.e. as if the `__far` applies to the function's return type.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

>  * Would relocation be required in setup.S (or a called C routine) to relocate the far code segment relocations? How hard would this be to write, and where is that table kept?

Most likely yes, `setup.S` will need to do the relocation.

The relocation information in an a.out comes after the initialized data bytes.  There are 3 blocks of relocations: `msh_trsize` bytes for the near text segment, `esh_ftrsize` bytes for the far text segment, then `msh_drsize` bytes for the data segment.

As for difficulty:  One problem I see with `setup.S` is that it has quite a fair amount of code duplication for a.out loading logic.  I suspect it will need to be refactored a bit before we try adding relocation support to it.

Thank you!

**Comment by tkchia** [comment]
>  * Since the block dev and char dev function arrays (blkdev_inode_operations) would also need to be far pointers, would just those entry points need to be far, or would everything they call need to be far as well? I suppose the same question for any far callback function calling a near function applies.

You can call near functions from far functions.  The internal mechanism for doing so is still rather big and slow and inefficient, but that may change in the future.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thank you for your comments, I have learned a lot.

While analyzing the operation of the far-to-near calling thunk, I had the following questions. Here is the thunk for reference:
```
        /* These routines must go into the near text segment, if at all.  */
        .text

        .global __ia16_far_call_thunk.bx.si
        .type   __ia16_far_call_thunk.bx.si, @function
        .global __ia16_far_call_thunk.bx.di
        .type   __ia16_far_call_thunk.bx.di, @function
__ia16_far_call_thunk.bx.si:
        pushw   %bp                     /* set up stack frame */
        movw    %sp,    %bp
        pushw   %bx                     /* preserve %bx and %cx */
        pushw   %cx
        movw    %si,    %cx             /* move stack args. size to %cx */
        jmp     0f
__ia16_far_call_thunk.bx.di:
        pushw   %bp
        movw    %sp,    %bp
        pushw   %bx
        pushw   %cx
        movw    %di,    %cx
0:                                      /* re-push stack arguments */
        jcxz    2f
        leaw    4(%bp), %bx
        addw    %cx,    %bx
        shrw    %cx
1:
        pushw   %ss:(%bx)
        decw    %bx
        decw    %bx
        loop    1b
2:
        movw    -4(%bp), %cx            /* reload %cx for callee */
        callw   *-2(%bp)                /* call function */
        movw    %bp,    %sp             /* tear down stack frame and return */
        popw    %bp
        lretw
```

- Why is the %ss: override necessary in the above code, when copying stack parameters? I understand the default segment the CPU uses is otherwise DS, but doesn't the compiler assume SS==DS for all code generated? There is lots of other code I've seen generated by gcc that uses (%bx) to address stack locations, usually after copying and using a pointer parameter accessed via XX(%bp). In general, since pointers are passed around between both the stack and data segments all the time, I can't see how most compiler-generated code could work without SS==DS.
- The top of the file states the thunk should always be placed in the near segment. Why is that, given that the compiled code always uses an lcall to the thunk? I think I may be getting confused as to what a near text segment actually is - is it just the default text segment in small model, or are there separate near segments in medium model as well? Either way, once executing in a far procedure outside a near segment, a far call would always be required to a thunk.

And separately - can a compiler option specify a far segment to be used for all routines in a source file (.o compilation unit), or does each procedure need to have an attribute associated with its declaration? My question applies to both small and medium model compilations, if different.

As I mentioned in https://github.com/jbruchon/elks/issues/705, it seems that a mixed-model approach for the ELKS kernel will be too inefficient because of the need for re-pushing stack parameters. It is possible that an init-only far segment could be used to save space, since the thunks and efficiency wouldn't matter and space be reclaimed. It's probably not worth the effort since elks/init/main.o is just under 1k bytes text size.

**Comment by ghaerr** [comment]
> One problem I see with setup.S is that it has quite a fair amount of code duplication for a.out loading logic. I suspect it will need to be refactored a bit before we try adding relocation support to it.

I looked harder at setup.S and it will fail a kernel load if the a.out header has any relocation entries. In addition, there is a comment on moving the code to "highest & aligned 64k". I don't understand the code exactly - does this move the kernel text/data/bss to reside at a full 64k boundary, wasting space above that? What will be needed for a kernel > 64k, say 70k, will all the space to the next 64k boundary be wasted above that? What is the need for 64k alignment?

It seems there are three distinct compiled cases needed to be handled and tested separately, when loading a > 64k kernel: CONFIG_ROMCODE, default REL_SYS, and !REL_SYS (which apparently doesn't relocate the kernel). I'm not sure how to test anything but the default REL_SYS case. It seems that applying the relocations for the REL_SYS case should not be very complicated. Were you thinking the REL_SYS code should be refactored, or refactoring to better address all three (hard to test) cases?

**Comment by ghaerr** [comment]
Hello @tkchia,

> The top of the file states the thunk should always be placed in the near segment. Why is that, given that the compiled code always uses an lcall to the thunk? I think I may be getting confused as to what a near text segment actually is - is it just the default text segment in small model, or are there separate near segments in medium model as well? 

Sorry for the above question - it seems I got myself confused thinking through the thunk code for the first time. I now understand the reason entire reason an `lcall` thunk is required is that any near procedure isn't CS addressable from a far procedure outside it's code segment. Since the lcall is required to load the CS register with the "near" segment, the parameters then need to be copied, before near-calling the procedure. Your recent changes to optimize a small fixed number of parameters will greatly increase that speed, thank you.

The process of calling near procedures from some (otherwise) far procedures outside their code segment brings me to the following thought, useful for a mixed model kernel: For those near routines in the same source file as the calling far routine, if those routines were in the same code segment (e.g., the source module compiled as a unit) as the calling procedure, then a simple near call would work, and no thunking necessary. Is that something the compiler can do now?

The idea would be that each "linked-in kernel module" would have its own code segment specified at compilation. Then, only the "interface-in" calls from another code segment or near procedure would require thunking, while all calls from the interface within the same module would be thunkless. Callbacks could be analyzed to determine if it were better to use a thunk-callout, or instead keep a near copy of the routine in the module (e.g., for the memcpy routine discussed below).

This capability could work well if were possible to group copies of kernel library routines (such as memcpy through __udivsi3 above) into the "linked-in module" as static routines, which would eliminate the need for thunking.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

Sorry for the delayed reply.

> This capability could work well if were possible to group copies of kernel library routines (such as `memcpy` through `__udivsi3` above) into the "linked-in module" as static routines, which would eliminate the need for thunking.

Well, such a thing will indeed be good to have.  But I suspect the GCC toolchain --- by itself --- is not yet smart enough to do so, unfortunately.

(The GNU compiler, assembler, and linker code are mainly geared towards systems with flat address spaces; it is a wonder that `gcc-ia16`'s medium model support works at all.)

It _might_ be possible though --- this is very speculative --- to essentially compile a "linked-in kernel module" as a world unto itself, then do some `a.out` manipulation and link them into the kernel image at the last step.  (This will be like macOS's prelinked kernel extensions, if you get my drift.)  But all this will probably require some additional machinery outside the normal compile-and-link process.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> The GNU compiler, assembler, and linker code are mainly geared towards systems with flat address spaces; it is a wonder that gcc-ia16's medium model support works at all.

I didn't realize that... thank you for continuing to be interested in adding support for segmented model issues, it is greatly appreciated for ELKS!

> It might be possible though --- this is very speculative --- to essentially compile a "linked-in kernel module" as a world unto itself, then do some a.out manipulation and link them into the kernel image at the last step.

How, more precisely, are you imagining this would work? Are we talking about a group of files being compiled medium model, then linked together, then somehow added to the kernel a.out file and having a known array of entry point procedures? Or would it be near code, with some trampoline code for calling procedures into it?

I'm guessing that an external method may not easily handle the callback functions easily, and am still probing to determine how much possibility there may be using the tools directly to accomplish the goal of using a mixed model approach for speed. We could now go directly with compiling everything medium model, but that's likely going to be a lot slower, is it not? Perhaps not... 

I don't yet understand how much the linker currently knows about multiple code segments. That is, can the linker handle differently-named far code segments, order them, and then link/generate the corresponding segment and offset relocation data?

I wanted to bring back the multi-model idea I proposed separately, to ask directly whether you see whether it could work with few modifications to the existing tools. I understand the compiler can already accept far text sections on a per-function basis. Can there be multiple names (sections, if you will), for these far text segments, which get combined by the linker later as above?

If so, then all functions in a "linked-in kernel module" could be specified to reside in a named "section" (text segment with same name). If near (static) functions could *also* be placed in that same section, then, with what seems to be a small(ish) compiler enhancement, when a far function in the same section calls one of those near functions, the compiler would check if the section name is the same, and in this case of a far function calling a near function in the same section, there would be no need for thunking, because the CS would be correct, and a near call could be emitted.

This mechanism would allow for what I think is needed to implement a mixed-model kernel with extreme efficiency, while using your existing thunk code when calling an "interface" function outside the current module (into a linked-in module). Of course, it would be nice to be able to specify an entire module being compiled with the same section name, but each function could explicitly specify the named text attribute if need be.

Thank you!
