### ISSUE TITLE
Can't compile x87 series FPU (older than i386) code.

### ISSUE THREAD

**Issue by TakedaHiromasa** [tkchia/gcc-ia16#67]
Hello!
I want to utilize i80286+i80287 FPU.
For example, I can't figure out how to compile the following code.
```
#include <stdio.h>

int main(void) {

  asm volatile ("finit");

  return 0;
}
```

If I specify x86-16bit as the target and compile it, I get the following error.
```
$ ia16-elf-gcc -mcmodel=medium -march=i286 -o FPU.EXE fpu.c
```
```
ld_st.c: Assembler messages:
ld_st.c:7: Error: `finit' is not supported on `i286'
```

I need the FPU for numerical calculations in my research.
Is there a way to use the x87 instruction?
If possible, I would like to link it with the C language.

**Comment by tkchia** [comment]
Hello @TakedaHiromasa,

> Is there a way to use the x87 instruction?
> If possible, I would like to link it with the C language.

Thanks for your report!  The assembler does not really support 80287 programming very well yet.  In the future I might propose a patch for stock GNU Binutils to beef up the `.arch` assembler directive to better support this.

Meanwhile, as a kind of hacky work-around, you can surround your FPU instructions with
```
.arch pentium
...
.arch i286
```
which will make the assembler (`as`) know how to assemble them.

Note that you might need to **manually [insert `fwait` instructions](https://kb.iu.edu/d/aann) at the appropriate places,** since the assembler does not really know that the FPU instructions are for an 80287, not a Pentium.

E.g.
```
#include <stdio.h>

int main(void)
{
	int i = 1;
	double d;
	__asm volatile(".arch pentium; "
		       "finit; "
		       "fild %1; "
		       "fstpl %0; "
		       "fwait; "
		       ".arch i286"
		       : "=m" (d) : "m" (i));
	printf("d = %f\n", d);
	return 0;
}
```

Thank you!

**Comment by tkchia** [comment]
Hello @TakedaHiromasa,

(In case you are wondering why I used
```
.arch pentium
...
.arch i286
```
instead of just
```
.arch pentium
...
```
--- I think that putting the assembler in `.arch pentium` mode permanently may cause the C compiler + assembler to erroneously produce 80386-only instructions at certain places.)

Thank you!

**Comment by TakedaHiromasa** [comment]
Thank you very much!
I didn't know that `.arch` can be specified in multiple places.
I was able to use i80287!

### TEST
(I couldn't find an emulator that could run FPU without problems, so I ran it on the actual machine.)
・PC-9801 DX/U2(i286+i287) + MS-DOS 5.0
```
#include <stdio.h>
#include <math.h>

int main(void){
  double a, b;
  double out;

  puts("Real number input:");
  printf("a=");
  scanf("%lf", &a);
  printf("b=");
  scanf("%lf", &b);

  __asm volatile(
    ".arch pentium;         "
    "finit;                 "
    "fld  %1;               " // %1 -> st0
    "fld  %2;               " // %2 -> st0, %1 -> st1
    "fadd %%st(1), %%st(0); " // st1 + st0 -> st0
    "fstpl %0;              " // st0 -> %0 & pop st0
    "fwait;                 "
    ".arch i286             "
    : "=m" (out) : "m" (a), "m" (b)
  );

  printf("FADD = %f\n", out);

  return 0;
}
```
<img src="https://user-images.githubusercontent.com/38904644/102180374-1a564f00-3eec-11eb-9dbb-182b8201d373.jpg" width=50%>

Thanks for the help!

**Comment by TakedaHiromasa** [comment]
Oops, the test code I just wrote loads a `double` value, so it might have needed to be a `fldl` instruction instead of `fld`.
