### ISSUE TITLE
Using far const (rodata) on another segment than the one pointed from DS

### ISSUE THREAD

**Issue by cocus** [tkchia/gcc-ia16#74]
Hi! I'm really amazed with this project. I really like it, at least for my tinkering needs :)
So, I'm trying to create my own BIOS/monitor for an 80C188 board. Right now I'm using [Wichit Sirichote's x86Bug](http://www.kswichit.com/C188/c188sbc.htm) because it was a good option for this embedded platform.
Now, I had a small glance at the [80x86 project](https://github.com/jamieiles/80x86) and I'm trying to port it (somehow) to this target. I have the code building (using Make, not CMake); and I've modified the loader so the flash gets addressed properly (using the CPU's integrated UCS control). I have a serial port connected to it, and I know that the code runs, at least until some C functions.
I saw that [they're defining some sections](https://github.com/jamieiles/80x86/blob/master/bios/bios.x) (0xc000, 0xb000 and 0xfff0), which should land on the upper segment (0xf000). If I'm not mistaken, the BIOS code is actually located on 0xc000, and 0xb000 is RW (stack, .data, .bss).
Since my board only has 128kB of RAM, I can't use the 0xf000:0xb000 area, since nothing (well, technically the flash) is mapped there.

Now, I've modified the loader to access the RW sections but on 0x0000:0xc000 for now (might move it later), and null the ds, ss, es (I don't know if it worked, but I hope it does :)).

Finally, the issue comes from the fact that the C code doesn't have a clue that I've changed the DS before launching it, thus initialized data (such as strings) are not found on the 0x0000 segment, but rather on the 0xf000 segment.

One solution would be to copy these to the RAM, but I would like to know if it's possible to mark const data to be on a specific segment, so the C code manages the DS (and probably SS, ES) for me.

If that's the case, do you mind sharing an example and how to compile it? I'm running the build with the following arguments passed to the C compiler/linker:
```
-ffunction-sections -Werror -ffreestanding -O2 -std=gnu99 -mtune=i80186 -march=i80186
```

And another solution would be to actually use the const data on the same segment as on the code, but use the RW on a different segment. Not sure how to achieve this (either by using the linker or adding something like __far as an attribute of all the globals). 
Thanks!

**Comment by tkchia** [comment]
Hello @cocus,

Thank you!  Regarding the issue, I recall that someone recently came up with another solution: to position the data segment such that part of it is in ROM, and another part is in RAM.

E.g. if you place it at `0xfe00:0x0000`, then `%ds` = `0xfe00` will be able to address `0x2000` bytes of ROM (`0xfe00:0x0000`---`0xfe00:0x1fff`) followed by `0xe000` bytes of RAM (`0xfe00:0x2000` etc. = `0x0000:0x0000` etc.).  Since you are working with an 80C188 chip, the linear addresses will wrap around at the 1 MiB mark, so this should do the right thing.

By default, at least for now (see my [write-up](https://github.com/tkchia/build-ia16/blob/db014ec21e7cdfe71a643870e2a4f8462dcb28ee/elf16-writeup.md) for more on the messy details), you can control the placement of the read-only data segment in the linker script, by setting
  * VMA = the final in-segment offset, at runtime, of the segment, and
  * LMA = the absolute offset of the segment's contents within your ROM image.

So most likely, in the above scenario, you would say something like
```
.rodata 0 : AT (0xe000) { ... }
```
in the linker script, because `.rodata` will start at offset `0` within some segment at runtime, but its contents will appear at `0xf000:0xe000` inside your ROM image.  (The linker does not really need to know about the `0xf000:` part.)

Of course, if you will also be having some data which are read/write but _also_ pre-initialized, you will still need to copy it from ROM to RAM in any case, because that is how the hardware works. :-|  You can say
```
.data 0x2000 : AT (_data_load) { ... }
```
and arrange for your code to copy the stuff starting at `0xf000:_data_load` to `0xfe00:0x2000`.  Thus both `.rodata` and `.data` are accessible through the same `%ds` value.

Thank you!

**Comment by cocus** [comment]
Excellent advice! I didn't know I could let the segment wrap around after 1MiB.
I've set my linker script as follows:
```
OUTPUT_FORMAT(binary)
OUTPUT_ARCH(i386)
ENTRY(_start)

SECTIONS {
    . = 0x0;
    /* with a CS=0xf000, this should land on 0xf0000+0xd000 = 0xfd000 */
    /* with a DS=0xfd00, this should land on 0xfd000+0x0000 = 0xfd000 */
    .text 0 : AT(0xd000) {
        bios_start = . ;
        *(.entry.text);
        
        . = ALIGN(4);
        *(.text);
        *(.text.*);
        
        . = ALIGN(4);
        *(.rodata*);
    }

    _data_load = . ;
    /* with a DS=0xfd00, this should land on 0xfd000+0x3000 = 0x100000 which wraps around to 0x00000 */
    .data 0x3000 : AT(_data_load) {
        data_start = . ;
        *(.data*);
        data_end = . ;

        . = ALIGN(4);
        bss_start = . ;
        *(.bss*);
        bss_end = . ;

        . = ALIGN(4);
        stack_end = . ;
        . = . + 0x100;
        stack_start = . ;
    }


    /* with a CS=0xf000, this should land on 0xf0000+0xfff0 = 0xffff0 */
    .reset 0xfff0 : AT(0xfff0) { 
        *(.reset.text);
    }
}
```

Then I've copied the putstr and putchar from the 80x86 bios project as follows:
```
void putchar(unsigned char c)
{
	while((inb(S0STS) & 8) == 0);
	outb(T0BUF, c);

    if (c == '\n')
        putchar('\r');
}

void putstr(const char *str)
{
    char p;

    for (p = *str; p != 0; ++str, p = *str)
        putchar(p);
}
```

Then on my "main" c code, I have the following:
```
volatile int global = 0xc0c0;
void root(void)
{
    global ^= 0xaa55;
    putchar('H');
    putchar('e');
    putchar('l');
    putchar('l');
    putchar('o');
    putchar('\n');

    putstr("This is a string boi!\n");
    while(1);
}
```

The startup code is setting ss, ds and es to 0xfd00 (since I felt that 0xfe00 wouldn't be enough code), then copying/initializing the appropriate sections with the following code:
```
    // Clear the BIOS stack space
    lea stack_start, %di    // location
    mov $0x100, %cx
    //sub $stack_end, %cx     // size
    xor %ax, %ax            // value
    std                     // backwards
    rep stosb
    cld             // forward

    // Clear bss
    lea bss_start, %di      // location
    mov $bss_end, %cx       //
    sub $bss_start, %cx     // size
    xor %ax, %ax            // value
    rep stosb

    // Initialize rw data
    mov %cs, %ax
    mov %ax, %ds    // ds = cs
    mov $data_start, %di
    mov $data_end, %cx
    sub $data_start, %cx
    mov $_data_load, %si
    rep movsb
    mov %es, %ax
    mov %ax, %ds    // ds = es

    movw $stack_start, %sp

    jmp root
```
I also write a single 'h' on the startup code to the serial port, just to know that it did make it thru.

If I leave the .text section to have its VMA = 0, the C code doesn't run at all!

Now, if I place the .text section on 0xd000, I would expect that my code prints the word "Hello" properly since I'm not using neither .rodata, nor .text directly (but rather pushing values into the stack). That seems to work, but the putstr() fails miserably.
```
hHello
<nonsense bytes>
```

I've ran a disassembly of the code, and for both cases I see the C code pushing different values for the putstr() function.
The first case (the one that didn't even write "Hello"), is the one that pushed a small value as the string offset (0x1e0 in my test); which I think it's okay, since with a DS=0xfd00, it'll read the ROM (address = 0xfd1e0).
But on the second test, where I placed the code on an incorrect VMA, the code does push a wrong value as the string offset (0xd1c5 or thereabouts).

In both cases, the behavior did make sense, but... for some reason the code that should've worked, didn't.

Other stuff that I found out while using the VMA = 0:
* .data is placed at 0x208, which is the size of the entire .text section; but it's not placed at 0xd000+0x208! (I thought the dot operator took care of that, but I might've not understand it properly)
* all the jmp's are referencing code that's after 0xd000, so I assume this couldn't crash the CPU
* SP is set to 0x3104 on the startup code (last line above the jmp root); I assume this is fine, since I've set a 0x100 bytes long stack inside .data, and that value would translate to 0x00104 if I'm not mistaken (SS = DS = ES = 0xfd00)

I really don't understand why the C code doesn't run when I set its section' VMA to 0.

If you can give me some hints, that'll be really appreciated!
I can give you more sources if needed, and I'm open to try some other changes!

**Comment by cocus** [comment]
I finally fixed it, I wasn't padding the resulting image correctly, but otherwise everything worked!

Thanks!
