### ISSUE TITLE
Static symbols in ELKS system map file?

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#76]
Hello @tkchia,

I'm playing with the idea of adding function symbols to the disassembly trace over at @mfld-fr's EMU86 project. 

Looking at the system.map file produced by the ld-gold linker, this would be fairly easy to parse, but of course none of the static symbols are included. That greatly decreases the utility of having function symbols displayed during traces.

Are you aware of a way a listing could be produced with the statics included? Perhaps using objdump or nm on the ELF file produced before the elf2elks conversion, provided the kernel was compiled -g?

[EDIT: I'm not sure the ELKS kernel will compile with -g only, it needs -Os. Would -g -Os optimize but leave statics in ELF debug/dwarf section?]

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Sorry to bother you with general questions about optimization and debug information; I will look up and gather that information myself.

> Perhaps using objdump or nm on the ELF file produced before the elf2elks conversion

I don't know how to access the ld.gold ELF file linker output prior to elf2elks conversion being run on it, is there a way to keep this intermediate file around for later post-processing by nm, objdump, etc.?

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

Sorry for the late reply!  I am not sure myself how to get `ld.gold` to output local symbols --- if I find out how, I will let you know.

> I don't know how to access the ld.gold ELF file linker output prior to elf2elks conversion being run on it, is there a way to keep this intermediate file around for later post-processing by nm, objdump, etc.?

Not yet --- but I should probably add such a thing.  (For now, as a quick hack, you can try stuffing an `elf2elks` symlink to (say) `/bin/true` in the `$PATH`.  This will leave the unconverted ELF file as the linker output.)

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> (For now, as a quick hack, you can try stuffing an elf2elks symlink to (say) /bin/true in the $PATH. This will leave the unconverted ELF file as the linker output.)

Thanks for the idea, I hadn't thought of that. I'll try looking at the ELF linker output and keep you posted as to whether an option to retain the ELF output might be useful :)

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

I was able to solve this issue over at EMU86 (https://github.com/mfld-fr/emu86/issues/70) without requiring an option to `ia16-elf-gcc` to retain an ELF file, because in ELKS the kernel build uses `ld.gold` directly, and `ia16-elf-nm` can be run in the Makefile before continuing with an explicit `elf2elks` conversion immediately afterwards. The explicit namelist on the ELF-format executable results in access to all static symbols, which solves the problem of the normal map file not containing private symbols.

Thanks for your help!

**Comment by ghaerr** [comment]
Hello @tkchia,

As discussed in #111, I have been using your suggested hack of substituting /bin/true for elf2elks to enable gaining access to the linker ELF output, so that ia16-elf-nm can be used to generate a symbol file that includes static symbols.

> is there a way to keep this intermediate file around for later post-processing by nm, objdump, etc.?
Not yet --- but I should probably add such a thing. 

I'd like to request adding an option that would either disable running elf2elks, keeping the ELF output, or perhaps just specify an output filename for the ELF output, while completing the link, whichever might be easier. This wasn't required previously, because the symbol table was for the ELKS kernel, which used a separate execution of ld.gold, with elf2elks following. For ELKS application programs, I think it is a bit too much to require running ld.gold explicitly (because of the complications of -M, -T, etc), rather than having ia16-elf-gcc continue to perform the link automatically.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

You can try using the new `-mno-post-link` option, which I added a few months earlier to `gcc-ia16` &mdash; this will make the GCC front-end skip any processing steps after the link sep.  You probably need to bump up the `gcc-ia16` version on the ELKS build, to get this option.

Thank you!
