### ISSUE TITLE
realpath() defined in stdlib.h, but not compiled into libc.a

### ISSUE THREAD

**Issue by rubenatch** [tkchia/gcc-ia16#78]
I was doing a small utility to run in DOS and I've found that, at least, realpath() doesn't work in 2011 April compilation.

The program compiles an run well using DJGPP (GCC version 9.3.0). Using i16gcc, the compiler finds no syntax errors, but the linker complains about realpath not present.

Will realpath() be included in gcc-ia16?

**Comment by tkchia** [comment]
Hello @rubenatch,

Yes, I do hope to implement some additional POSIX-ish functions such as `realpath (`...`)`, `uname (·)`, etc., in the `gcc-ia16` toolchain some time.  These will likely eventually go into `libc.a` or into [`libi86`](https://github.com/tkchia/libi86).

Thank you!
