### ISSUE TITLE
launchpad/Binaries for Ubuntu 21.04 Hirsute Hippo?

### ISSUE THREAD

**Issue by LowLevelMahn** [tkchia/gcc-ia16#80]
is it possible to add also Hippo to the supported distro?

or is it trivial to build from source?

**Comment by tkchia** [comment]
Hello @LowLevelMahn,

I do not really plan to add Launchpad builds for non-LTS versions of Ubuntu yet &mdash; but perhaps I will consider.

In the meantime, one way you can build from source is to use the [`build-ia16`](https://github.com/tkchia/build-ia16) project.  Not trivial, but hopefully not too hard either. :-)  If you check out this project in a ...`/build-ia16` directory and follow the general workflow, you should get a compiled and "installed" toolchain under ...`/build-ia16/prefix/`.

Thank you!

**Comment by LowLevelMahn** [comment]
i'll give it a try - hopefully my PC + VM is strong enough to build a full gcc in tolerable time :)

**Comment by LowLevelMahn** [comment]
got it working - so thanks
