### ISSUE TITLE
ICE for simple code using far pointers with -O3

### ISSUE THREAD

**Issue by LinoMastro** [tkchia/gcc-ia16#86]
```
void test(char __far *buf) {
    for (int x = 0; x < 16; x++) {
        buf[x] = 0;
    }
}
```

When compiled with -O3 causes an ICE:

```
$ ia16-elf-gcc -c bug_gcc.c -O3
trying to convert pointer or address in address space 0
with unexpected mode:
(reg/v/f:SI 24 [ buf ])
bug_gcc.c: In function ‘test’:
bug_gcc.c:1:6: internal compiler error: in convert_memory_address_addr_space_1, at explow.c:315
 void test(char __far *buf) {
      ^~~~
Please submit a full bug report,
with preprocessed source if appropriate.
```

This happens with the latest 6.3.0-20211005 from Launchpad, but I can reproduce the problem with older builds from a few months ago too.

The code above repeats the loop 16 times, reducing this to only 3 times or less causes the ICE to disappear and -O3 then produces correct code.

The issue doesn't occur with -O1, -O2 or -Os.

**Comment by tkchia** [comment]
Hello @LinoMastro,

Thanks for the report.  It seems `gcc-ia16` was (wrongly) trying to rewrite the loop as a `memset (`...`)` call, even though the buffer to fill was a far buffer.  I would need to see how to stop GCC from doing that.

Thank you!

**Comment by LinoMastro** [comment]
I know little about GCC workings but is it by any chance easier to provide GCC with an internal variant of memset that accepts far pointers, rather than stopping the optimizer from using memset in these cases?

**Comment by tkchia** [comment]
Hello @LinoMastro,

That is kind of possible &mdash; and in fact `gcc-ia16` already does something like what you describe for `memcpy (`...`)`-like operations.  If the C code tries to copy one far memory block to another, the back-end will try to turn it into a `rep; movsw` operation.

I (or we) just need to code up something similar for `memset (`...`)`-like operations...

Thank you!
