### ISSUE TITLE
TSR with -mtsr: Loading flat .COM style executable into a block smaller than 64 KiB (eg with LH) results in crash

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#87]
I reported this to FreeDOS SHARE at first because I didn't know what was the cause of this. Turns out the compiler is to blame. Read the details at https://github.com/FDOS/share/issues/7 and here's the last comment quoted:

> Got it! The different UMB layout makes it so SHARE is loaded into a block smaller than 64 KiB. Here's the error:
> 
> ```
> Welcome to dosemu2!
>     Build 2.0pre8-20190827-1234-g0984731c9
> G:\>lh ldebug share.com
> -dm
> PSP: F068
> 02B4 4D 0008 0019    400 B SD
> 02CE 4D 02CF 0091    2 KiB COMMAND
> 0360 4D 0361 1B34  108 KiB LDEBUG
> 1E95 4D 0000 8169  517 KiB
> 9FFF 4D 0008 3100  196 KiB SC
> D100 4D 0008 1EFF  123 KiB SC
> F000 4D 02CF 0040   1024 B COMMAND
> F041 4D 0361 0012    288 B LDEBUG
> F054 4D F068 0012    288 B SHARE
> F067 5A F068 0B98   46 KiB SHARE
> -r
> AX=0000 BX=0000 CX=0F5A DX=0000 SP=B97E BP=0000 SI=0000 DI=0000
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0100 NV UP EI PL ZR NA PE NC
> F068:0100 E9150A            jmp     0B18
> -t
> AX=0000 BX=0000 CX=0F5A DX=0000 SP=B97E BP=0000 SI=0000 DI=0000
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0B18 NV UP EI PL ZR NA PE NC
> F068:0B18 BE5810            mov     si, 1058
> -
> AX=0000 BX=0000 CX=0F5A DX=0000 SP=B97E BP=0000 SI=1058 DI=0000
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0B1B NV UP EI PL ZR NA PE NC
> F068:0B1B BFDEFE            mov     di, FEDE
> -
> AX=0000 BX=0000 CX=0F5A DX=0000 SP=B97E BP=0000 SI=1058 DI=FEDE
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0B1E NV UP EI PL ZR NA PE NC
> F068:0B1E B99602            mov     cx, 0296
> -
> AX=0000 BX=0000 CX=0296 DX=0000 SP=B97E BP=0000 SI=1058 DI=FEDE
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0B21 NV UP EI PL ZR NA PE NC
> F068:0B21 FD                std
> -
> AX=0000 BX=0000 CX=0296 DX=0000 SP=B97E BP=0000 SI=1058 DI=FEDE
> DS=F068 ES=F068 SS=F068 CS=F068 IP=0B22 NV DN EI PL ZR NA PE NC
> F068:0B22 F3A5              rep     movsw
> -h linear es:di+2
> 00100560  decimal: 1049952
> -h linear f068+b98:0
> 000FC000  decimal: 1032192
> -
> ```
> 
> The linear address behind the last-written word is in the HMA (at 10_0560h), extending fairly far behind the end of SHARE's MCB (at F_C000h). I will report this for the compiler, it really shouldn't assume it has 64 KiB available for a flat .COM style executable.

**Comment by ecm-pushbx** [comment]
Note that if you were to build an MZ .EXE style executable then it would be possible to indicate the memory requirements in the MZ header, so if the compiler and linker cooperate then the DOS can know exactly how large a memory block is needed. This would make LH work as expected (though of course it might load the program in an LMB if no UMB is large enough).

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Oops &mdash; thanks for the report!  I will fix this in `newlib-ia16` soon.

**Comment by andrewbird** [comment]
> it really shouldn't assume it has 64 KiB available for a flat .COM style executable.

I see, yes I made that assumption when playing with the linker script initially as I always had lots more than that available and never considered that it could be less than 64K. I presume this is smaller because `lh` is being used, if as you mention a .EXE gives info to the loader about how much is needed, how is the memory requirement for a .COM determined by the loader? If it's filesize that would seem inadequate as share uses dynamic memory allocation.

**Comment by tkchia** [comment]
Hello @andrewbird, hello @ecm-pushbx,

> how is the memory requirement for a .COM determined by the loader? If it's filesize that would seem inadequate as share uses dynamic memory allocation.

Basically yes &mdash; it seems both MS-DOS 2.0 and FreeDOS only care about the `.com` file size.  Both kernels will try to load the `.com` file in the largest available MCB.  So the burden ends up being on the `.com` program to check if it is loaded in a memory block that gives the program enough leeway.

(It will probably take a while for me to fix up `newlib-ia16`.  The startup code likely needs to check for available memory after, not before, any check for MS-DOS 2+, so that it does not weird out on DOS 1.x...)

Thank you!

**Comment by ecm-pushbx** [comment]
> > it really shouldn't assume it has 64 KiB available for a flat .COM style executable.
> 
> I see, yes I made that assumption when playing with the linker script initially as I always had lots more than that available and never considered that it could be less than 64K. I presume this is smaller because `lh` is being used,

Yes.

> if as you mention a .EXE gives info to the loader about how much is needed, how is the memory requirement for a .COM determined by the loader? If it's filesize that would seem inadequate as share uses dynamic memory allocation.

Yes, the DOS will insure that a memory block is large enough for the PSP + entire file + maybe a bit for the stack.

**Comment by ecm-pushbx** [comment]
> Hello @andrewbird, hello @ecm-pushbx,
> 
> > how is the memory requirement for a .COM determined by the loader? If it's filesize that would seem inadequate as share uses dynamic memory allocation.
> 
> Basically yes — it seems both MS-DOS 2.0 and FreeDOS only care about the `.com` file size. Both kernels will try to load the `.com` file in the largest available MCB. So the burden ends up being on the `.com` program to check if it is loaded in a memory block that gives the program enough leeway.
> 
> (It will probably take a while for me to fix up `newlib-ia16`. The startup code likely needs to check for available memory after, not before, any check for MS-DOS 2+, so that it does not weird out on DOS 1.x...)

Actually you can simply check whether `sp` is high enough in the first segment for your relocation needs plus some stack space. If `sp` starts out as FFFEh you have a full 64 KiB or larger memory block.

However, it is really better to use an MZ header because then DOS can tell before loading the file that a candidate block would be too small. If you use a flat executable and check the space yourself the best you can do is error out. (Or relocate your process, but that may be a bit too involved.) You can wrap a given flat executable in an MZ header without much work.

**Comment by tkchia** [comment]
Hello @ecm-pushbx, hello @andrewbird,

OK &mdash; I have added a new [commit](https://github.com/tkchia/newlib-ia16/commit/caff3329acf95227c59580f13c90bc655372aee2) for `newlib-ia16` which now checks if there is enough memory, and errors out (silently) otherwise.  The PPA should also have been updated now.

> If you use a flat executable and check the space yourself the best you can do is error out. (Or relocate your process, but that may be a bit too involved.) You can wrap a given flat executable in an MZ header without much work.

That is quite true, though I am not sure though there is really that much advantage from using an `MZ` header in contrast to adding some explicit code in a `.com` file.  In particular, I doubt that DOS will be able to find a more suitable candidate block for loading the program if it were an `MZ` file &mdash; the MCB allocated to a `.com` file is likely to be the largest available anyway.  But perhaps I am missing something here. 😐

Thank you!

**Comment by ecm-pushbx** [comment]
> OK — I have added a new [commit](https://github.com/tkchia/newlib-ia16/commit/caff3329acf95227c59580f13c90bc655372aee2) for `newlib-ia16` which now checks if there is enough memory, and errors out (silently) otherwise. The PPA should also have been updated now.

I'm not satisfied with that. It would be much better to show an error message.

> > If you use a flat executable and check the space yourself the best you can do is error out. (Or relocate your process, but that may be a bit too involved.) You can wrap a given flat executable in an MZ header without much work.
> 
> That is quite true, though I am not sure though there is really that much advantage from using an `MZ` header in contrast to adding some explicit code in a `.com` file. In particular, I doubt that DOS will be able to find a more suitable candidate block for loading the program if it were an `MZ` file — the MCB allocated to a `.com` file is likely to be the largest available anyway. But perhaps I am missing something here. 😐

In the LH case it may very well be that *the largest UMB* isn't large enough. But with the proper MZ header allocation info, DOS knows to allocate an LMB (regular memory block that is not an UMB) instead, and the error case is avoided. I think users would probably prefer LH to just "fall back" to LMA allocation instead of the program silently terminating.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

> It would be much better to show an error message.

OK &mdash; let me see how I can fix that.

> But with the proper MZ header allocation info, DOS knows to allocate an LMB (regular memory block that is not an UMB) instead, and the error case is avoided.

Hmm, OK.  In that case perhaps I should add to `gcc-ia16` a sort of "tiny model but `MZ`" option to produce such programs.

Thank you!

**Comment by ecm-pushbx** [comment]
I just [updated my toolchain](https://github.com/tkchia/libi86/issues/11). It appears that the error message is wrongly addressed somehow:

```
E:\>ldebug share.com
-r sp c000
-r
AX=0000 BX=0000 CX=0F6E DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0100 NV UP EI PL ZR NA PE NC
1FC5:0100 E9110A            jmp     0B14
-p
AX=0000 BX=0000 CX=0F6E DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B14 NV UP EI PL ZR NA PE NC
1FC5:0B14 B430              mov     ah, 30
-
AX=3000 BX=0000 CX=0F6E DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B16 NV UP EI PL ZR NA PE NC
1FC5:0B16 CD21              int     21
-
AX=0A07 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B18 NV UP EI PL ZR NA PE NC
1FC5:0B18 2C02              sub     al, 02
-
AX=0A05 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B1A NV UP EI PL NZ NA PE NC
1FC5:0B1A 98                cbw
-
AX=0005 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0000 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B1B NV UP EI PL NZ NA PE NC
1FC5:0B1B 95                xchg    ax, bp
-
AX=0000 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B1C NV UP EI PL NZ NA PE NC
1FC5:0B1C B8E0FF            mov     ax, FFE0
-
AX=FFE0 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B1F NV UP EI PL NZ NA PE NC
1FC5:0B1F 39C4              cmp     sp, ax
-
AX=FFE0 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B21 NV UP EI NG NZ NA PO CY
1FC5:0B21 720A              jb      0B2D                                jumping
-
AX=FFE0 BX=FD2A CX=0000 DX=0000 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B2D NV UP EI NG NZ NA PO CY
1FC5:0B2D BA88FD            mov     dx, FD88
-
AX=FFE0 BX=FD2A CX=0000 DX=FD88 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B30 NV UP EI NG NZ NA PO CY
1FC5:0B30 B409              mov     ah, 09
-
AX=09E0 BX=FD2A CX=0000 DX=FD88 SP=C000 BP=0005 SI=0000 DI=0000
DS=1FC5 ES=1FC5 SS=1FC5 CS=1FC5 IP=0B32 NV UP EI NG NZ NA PO CY
1FC5:0B32 CD21              int     21
-d ds:dx l 10
1FC5:FD80                         -00 00 00 00 00 00 00 00         ........
1FC5:FD90  00 00 00 00 00 00 00 00-                        ........
-
```

Running that interrupt call outputs a lot of garbage.

**Comment by ecm-pushbx** [comment]
It appears the message is addressed with the offset it will have after the relocation. But when it is used then the relocation has not happened yet.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Argh &mdash; thanks for the report, and sorry for the silly mistake.  This should now be fixed in my latest `newlib-ia16` commit (https://github.com/tkchia/newlib-ia16/commit/bfa3299fb178fe902c93f9a43f2b6d1bb7d08bae).

**Comment by andrewbird** [comment]
I expect that using lh with share (both gcc and tcc variants) that there will be a range of free upper memory block sizes where it could be loaded (based on filesize), but at init time will find there's not enough memory to allocate the lock and share tables. I don't think that problem goes away by using an mz .exe as we don't know the memory requirements until its arguments are parsed.

Thank you!

**Comment by ecm-pushbx** [comment]
> This should now be fixed in my latest `newlib-ia16` commit ([tkchia/newlib-ia16@bfa3299](https://github.com/tkchia/newlib-ia16/commit/bfa3299fb178fe902c93f9a43f2b6d1bb7d08bae)).

Confirmed, it works as expected now.

> I expect that using lh with share (both gcc and tcc variants) that there will be a range of free upper memory block sizes where it could be loaded (based on filesize), but at init time will find there's not enough memory to allocate the lock and share tables. I don't think that problem goes away by using an mz .exe as we don't know the memory requirements until its arguments are parsed.

Good catch. What is the maximum size needed by the resident SHARE? The check done by the updated newlib already requires FFE0h bytes in the first segment. (Nearly 64 KiB.) I tried loading it with the maximum switch values as `share /f:62000 /l:3800` but I suspect this is not correctly supported (though no error or warning is displayed); the resulting resident MCB is 0BEBh paragraphs (47 KiB).

**Comment by ecm-pushbx** [comment]
Trying only with the /F: switch appears to work better. I found that it must be passed as 59_970 or less to succeed. Resulting resident memory block is F6Dh paragraphs (61 KiB).

```
E:\>share /f:59971
SHARE: out of memory!
E:\>share /f:59970
SHARE installed.
E:\>ldebug /c='@dm;@q'
PSP: 2D6C
029B 4D 0008 0018    384 B SD
02B4 4D 1237 0013    304 B LDEBUG
02C8 4D 02C9 0F6D   61 KiB SHARE
1236 4D 1237 1B34  108 KiB LDEBUG
2D6B 5A 2D6C 7293  458 KiB DEBUGGEE
9FFF 4D 0008 2100  132 KiB SC
```

**Comment by andrewbird** [comment]
> I tried loading it with the maximum switch values as share /f:62000 /l:3800 but I suspect this is not correctly supported (though no error or warning is displayed); the resulting resident MCB is 0BEBh paragraphs (47 KiB).

I'd have to check but it seems like some calculation is being truncated somewhere as it doesn't exceed the maximum memory allocation (64k - resident code and data).
