### ISSUE TITLE
libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#91]
I noticed this some time ago and fixed it at the time by modifying this symlink. Think it should read `../stamp-bits` but read just `stamp-bits` (ie referring to itself). But I suppose you may want to know about it.

```
grep: ./build-ia16/build2/ia16-elf/rtd/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/regparmcall/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/regparmcall/any_186/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/pmode/rtd/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/pmode/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
grep: ./build-ia16/build2/ia16-elf/pmode/regparmcall/libstdc++-v3/include/bits/stamp-bits: Too many levels of symbolic links
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Thanks!  I see that the problem has already been fixed in upstream GCC (https://github.com/gcc-mirror/gcc/commit/97b99f9c773a97d36febcc3136dbf286e821a3d1).  Most probably I will just need to somehow pull this fix into the `gcc-ia16` tree.

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

I have cherry-picked and pulled the fix from upstream GCC, as https://github.com/tkchia/gcc-ia16/commit/8f98e1713ae05a4920b5eac36d12838c1f09503a .  Thank you!
