### ISSUE TITLE
Missed optimisation: test ax, ax is more idiomatic than and ax, ax

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/gcc-ia16#93]
While stepping through a program compiled by ia16 gcc I have noticed that it compiles checks for zero values in registers to eg `and ax, ax`. However, `test ax, ax` should be preferred because it results in the same status flags but is more idiomatic. Logically `test` probably "knows" earlier than `and` that the register is not changed by the instruction. There are also real world advantages because the `test` instruction [is supported more](https://stackoverflow.com/questions/33721204/test-whether-a-register-is-zero-with-cmp-reg-0-vs-or-reg-reg/33724806#33724806) as a zero check idiom than `or` or `and` with the same register.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Hmm... OK.  This change should not be too hard to make. :slightly_smiling_face:   Thank you!

**Comment by ecm-pushbx** [comment]
Tested after updating and rebuilding gcc1, newlib, libi86, and gcc2 today, it does seem to use `test ax, ax` now.
