### ISSUE TITLE
GCC optimization out of null pointer test

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#96]
Hello @tkchia,

Are you aware of the default gcc behavior, shown below, where if a pointer is dereferenced, code will not be generated for testing the pointer itself against NULL afterwards? For instance, the following program, and it's generated output:
```
struct a {
    int member;
};
void test(void)
{
    struct a *p = malloc(sizeof(struct a));
    printf("%p, %d\n", p, p->member);
    if (p) { // <-- no code generated for this test if above printf is compiled
        printf("Path always taken!\n");
    }
}
```
```
000000e4 <test>:
  e4:   b8 02 00                mov    $0x2,%ax
  e7:   50                      push   %ax
  e8:   e8 fe ff                call   e9 <test+0x5>
            e9: R_386_PC16  malloc
  eb:   89 c3                   mov    %ax,%bx
  ed:   ff 37                   pushw  (%bx)
  ef:   50                      push   %ax
  f0:   b8 a2 00                mov    $0xa2,%ax
            f1: R_386_16    .rodata.str1.1
            f1: R_386_SUB16 .rodata.str1.1!
  f3:   50                      push   %ax
  f4:   e8 fe ff                call   f5 <test+0x11>
            f5: R_386_PC16  printf
  f7:   b8 aa 00                mov    $0xaa,%ax
            f8: R_386_16    .rodata.str1.1
            f8: R_386_SUB16 .rodata.str1.1!
  fa:   50                      push   %ax
  fb:   e8 fe ff                call   fc <test+0x18>
            fc: R_386_PC16  puts
  fe:   83 c4 0a                add    $0xa,%sp
 101:   c3                      ret    
 ```
If malloc returns NULL, the above code will print 000000, [garbage]. Then the if statement is always taken, even though p is actually NULL.

If the first printf is commented out, the following (IMO more correct) code is generated:
```

000000e4 <test>:
  e4:   b8 02 00                mov    $0x2,%ax
  e7:   50                      push   %ax
  e8:   e8 fe ff                call   e9 <test+0x5>
            e9: R_386_PC16  malloc
  eb:   83 c4 02                add    $0x2,%sp
  ee:   21 c0                   and    %ax,%ax
  f0:   74 0a                   je     fc <test+0x18> // <--- p tested here
  f2:   b8 a2 00                mov    $0xa2,%ax
            f3: R_386_16    .rodata.str1.1
            f3: R_386_SUB16 .rodata.str1.1!
  f5:   50                      push   %ax
  f6:   e8 fe ff                call   f7 <test+0x13>
            f7: R_386_PC16  puts
  f9:   83 c4 02                add    $0x2,%sp
  fc:   c3                      ret
```

My question is: is there a way to turn this default behavior off, and/or a warning be generated in this case?

For 8086, I ran into a problem where the first printf was an optional "debug()" call that was sometimes defined to be a call to printf, other times, nothing (the debug statement dereferenced the pointer without checking for null). That ended up changing the behavior of the null pointer test below it, and it took quite a while to debug what was going on. I think it would be useful to have options for such optimization being performed, especially since the 8086 won't fault on a NULL pointer dereference like 32-bit systems will.

On a separate note entirely, notice in the first ASM output, the additional compiler optimization of turning the second call to `printf` to a call to `puts`, since there was no % format specifier used. This could also be dangerous if used in operating system or other applications where the libc printf was defined elsewhere, but puts was called instead.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> I think it would be useful to have options for such optimization being performed, especially since the 8086 won't fault on a NULL pointer dereference like 32-bit systems will.

I believe the GCC `-Wnull-dereference` option should work.  There is also `-fno-delete-null-pointer-checks`, which will actually retain the null pointer checks.  Perhaps the latter should be a default for IA-16.

> This could also be dangerous if used in operating system or other applications where the libc printf was defined elsewhere, but puts was called instead.

This optimization is probably because GCC considers `printf` as sort of a "built-in function", with special logic.  Try using something like `-fno-builtin-printf`.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> I believe the GCC -Wnull-dereference option should work. There is also -fno-delete-null-pointer-checks, which will actually retain the null pointer checks. 

I just tested the former, no change. However, the latter works and code is produced to test the pointer.

> Perhaps the latter should be a default for IA-16.

I would vote for that, as an unintentional pointer dereference causes less harm than the compiler then assuming there is no need to test for NULL, and there's never a hardware fault, which is likely what this optimization depended upon.

In the meantime, I think it might be a good idea to add -fno-delete-null-pointer-checks to ELKS for both kernel and application compiles. It would be interesting if there was an easy way to see what code changes there might be throughout the system, as this would point out coding errors of pointer dereferences before null checking, which would be quite helpful for 8086 programmers.

> Try using something like -fno-builtin-printf.

I will try that. Is there an option to specify that a replacement function should be treated like `printf`, for instance `printk`, which might check format strings? That would be kind of nice. Except that we would want to seperate the association between printf and puts as well.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Is there an option to specify that a replacement function should be treated like `printf`, for instance `printk`, which might check format strings?

You can place `__attribute__ ((__format__ (`...`)))` attribute specifications on the function prototype.  These are documented in the GCC info file (`info gcc`).

The GNU C Library uses these function attributes to mark various functions as `printf`-like, e.g.:
```
#ifdef __USE_XOPEN2K8
/* Write formatted output to a file descriptor.  */
extern int vdprintf (int __fd, const char *__restrict __fmt,
		     __gnuc_va_list __arg)
     __attribute__ ((__format__ (__printf__, 2, 0)));
extern int dprintf (int __fd, const char *__restrict __fmt, ...)
     __attribute__ ((__format__ (__printf__, 2, 3)));
#endif
```

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

I performed some additional testing over at ELKS, using the `-fno-delete-null-pointer-checks` and `-Wnull-dereference` options. Recompiling the entire system and all applications, then looking for any differences, resulted in identifying a single kernel coding bug in fs/namei.c, shown here prior to its fix:
```
static int follow_link(struct inode *dir, register struct inode *inode,
                int flag, int mode, struct inode **res_inode)
{
    register struct inode_operations *iop = inode->i_op;
    int error = 0;

    *res_inode = inode;
    if (!dir || !inode) {
        iput(inode);
        *res_inode = NULL;
        error = -ENOENT;
    } else if (iop && iop->follow_link) {
        dir->i_count++;
        error = iop->follow_link(dir, inode, flag, mode, res_inode);
    }
    iput(dir);
    return error;
}
```
With that recoded to eliminate the pointer dereference prior to checking for it being NULL, there are no differences in the kernel or application binaries, which I view as a good thing. Thus, I will be setting both options on by default. I thought you might like to know that there seems little risk in setting this as a default for gcc-ia16, at least for ELKS, should you decide to do so.

[EDIT: The best solution for gcc-i1a6 seems to be, if possible, that with `-Wnull-dereference` and `-fno-delete-pointer-checks` on, the compiler acts as though `-fdelete-pointer-checks` is on but issues a warning, instead of not generating code on subsequent pointer checks for NULL. That would have caught this coding error.]

As a side note, the only difference in the kernel system.map file between the compiles with and without the options is now:
```
diff system.map /tmp
2947,2948c2947,2948
< .symtab         0x00000000    0x21370
<  ** symtab      0x00000000    0x21370
---
> .symtab         0x00000000    0x21390
>  ** symtab      0x00000000    0x21390
```
Not sure why exactly that is, but seems quite minor.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

I have pushed a commit for `gcc-ia16` that makes it default to retaining null pointer checks: https://github.com/tkchia/gcc-ia16/commit/223c9914d3959650292c8f6fd978ce4ff00cd87b .  I have run it through the C language regression tests; you may want to use it for ELKS.  Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> I have pushed a commit for gcc-ia16 that makes it default to retaining null pointer checks
> you may want to use it for ELKS.

Thank you! I will update the toolchain on your next formal release. The default compilation rules currently specifies `-fno-delete-null-pointer-checks`, which will be able to be removed, and there is an old issue with tools not compiling (#774) which I will reach out to see whether it ever got resolved.
