### ISSUE TITLE
Question and problem with floating point

### ISSUE THREAD

**Issue by ghaerr** [tkchia/gcc-ia16#98]
Hello @tkchia,

We recently implemented [floating point output support](https://github.com/jbruchon/elks/pull/1246) via printf/sprintf/vfprintf in ELKS libc, which required adding an implementation of ecvt/fcvt, which are dragged in (for now) using a pointer to another function __fp_print_func, which processes the decimal point placement.

I've had to resort to temporarily adding the libc ecvt.o directly to the [Makefile](https://github.com/jbruchon/elks/blob/98fac601ebc1376eeba4ca6d0bc254fb3cdbe3cb/elkscmd/misc_utils/Makefile#L25-L29) for a testing program 'float', used to test the library:
```
# FIXME work around undefined 'memcpy' in libgcc.a
ECVT=../../libc/build-ml/elkslibc/misc/ecvt.o
float: float.o
	$(LD) $(LDFLAGS) -o float float.o $(ECVT) $(LDLIBS)
```
Without this workaround, the link for `float` fails, as it seems the _fpadd_parts function calls memcpy, which isn't found.
```
/Users/greg/net/elks-gh/cross/lib/gcc/ia16-elf/6.3.0/elkslibc/libgcc.a(_addsub_df.o):
        function _fpadd_parts: error: undefined reference to 'memcpy'
```
Is there an issue with libgcc.a not being topologically sorted properly such that memcpy is not found? I've tried adding -lgcc twice but get the same error.

Separately, I have a question about using `float` vs `double` with ia16-elf-gcc. It seems that the code produced when only double is used is quite compact, whereas float ends up calling internal expansion and truncation routines for every float access. Can you give a recommendation on this? For our newly ported BASIC interpreter, using only doubles resulted in a significant code size reduction, by executing everything in 64 bit double. However, this increases the embedded storage for each float variable. Perhaps the lower level routines only use double, and thus the required extra overhead?

Finally, there was a question posed about whether hardware floating point is or will be supported. Can you comment on that?

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Is there an issue with libgcc.a not being topologically sorted properly such that memcpy is not found?

Yes &mdash; and this is a bug in the `gcc-ia16` front-end.  Sorry for that.  The linker command line says `-lc -lgcc`, but it should probably be `-lc -lgcc -lc`.  I should fix this when I get around to it.

> float ends up calling internal expansion and truncation routines for every float access. Can you give a recommendation on this?

Maybe let me try to look into this problem.  One possibility is that "default promotion" from `float` to `double` might be happening in some cases, and responsible for the bloat &mdash; the GCC info page says,

> It is easy to accidentally do computations with `double` because floating-point literals are implicitly of type `double`.  For example, in:
> ```
> float area(float radius)
> {
>    return 3.14159 * radius * radius;
> }
> ```
> the compiler performs the entire computation with `double` because the floating-point literal is a `double`.

But I guess there might be other possible causes for this issue.  Do you have a smallish code snippet which can exhibit the problem?

> Finally, there was a question posed about whether hardware floating point is or will be supported.

I do not have any plans at the moment to add hardware floating point support to `gcc-ia16`.  (This is not very trivial, unfortunately, and I am not sure I have the time and energy for it.  But if someone else wants to add this feature, I can try to help.)

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

> The linker command line says -lc -lgcc, but it should probably be -lc -lgcc -lc. 

Thanks, I hadn't tried adding -lc and will do so in that link line.

This means that the ELKS libc memcpy would be used, correct? Is that always the case, even when GCC emits its own (internal) calls to memcpy, or when (in this case) when an internal float routine requires memcpy? That seems strange, as it implies that there may be two different versions of memcpy used, ELKS libc vs gcc libc, which doesn't seem correct, unless the libc version always overrides the gcc version, or there is no gcc version.

> floating-point literals are implicitly of type double.
> But I guess there might be other possible causes for this issue. Do you have a smallish code snippet which can exhibit the problem?

I didn't know that, thank you. I'll check to see whether that's an issue and if not, post a code snippet.

> ... add hardware floating point support to gcc-ia16. I am not sure I have the time and energy for it. 

No problem! I understand completely, I think the request was mostly for information. I think the existing floating port support is definitely good enough, and it seems to work quite well :) I do plan on adding a (C) math library though.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

It seems that a good amount of the extra code generated I was looking at was the result of conversion of double literals to float. However, the opposite seems to be occurring when passing floats as arguments to a function, unless that function's arguments are declared float.

Thus, the problem pretty much goes away with careful coding using (float) casting in front of floating point literals and only passing float only to functions declared with float arguments. However, it seems that vararg functions, like printf, still have a problem with expanding float -> double, even when cast (float) by the caller. Do you know of a way around that?  I'm not sure if this is to do with varargs, or the special handling of printf by gcc.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> However, it seems that vararg functions, like printf, still have a problem with expanding float -> double, even when cast (float) by the caller. Do you know of a way around that? I'm not sure if this is to do with varargs, or the special handling of printf by gcc.

From what I understand, the C standard pretty much mandates that all variadic arguments to variadic functions must go through the `float` &rightarrow; `double` "default promotion".  (See Section 6.5.2.2 of the final draft of C11, [N1570](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf).)

I do not know of any really good way to work around this.  If you have a variadic function &mdash; not `printf` &mdash; that might want to process `float` variadic arguments, one (silly) way might be to arrange to wrap up the `float` 's in some `struct` type.  The wrapped-up `float` 's will then not be subject to default argument promotion.

Thank you!

**Comment by ghaerr** [comment]
Thank you for your help @tkchia, as a result everything is straightened out and working well!

**Comment by tkchia** [comment]
Hello @ghaerr,

>  > The linker command line says `-lc -lgcc`, but it should probably be `-lc -lgcc -lc`.
> Thanks, I hadn't tried adding -lc and will do so in that link line.

By the way, I have now fixed this particular problem on the `gcc-ia16` end, with commit https://github.com/tkchia/gcc-ia16/commit/1291757c78ec78b75677731cdd8ef0f434ab2ee2 .  You should now be able to compile the `ecvt` code without having to add `-lc` to the link command (which is as it should be).

Thank you!
